<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG61xh05\PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG61xh05/PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG61xh05.legacy');

    return;
}

if (!\class_exists(PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG61xh05\PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer::class, PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer::class, false);
}

return new \ContainerG61xh05\PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer([
    'container.build_hash' => 'G61xh05',
    'container.build_id' => '300b80b9',
    'container.build_time' => 1751212368,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG61xh05');
