<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluDocumentManager_Command_Initialize_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_document_manager.command.initialize.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_document_manager.command.initialize.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:document:initialize', [], 'Initialize the content repository/repositories.', false, #[\Closure(name: 'sulu_document_manager.command.initialize', class: 'Sulu\\Bundle\\DocumentManagerBundle\\Command\\InitializeCommand')] fn (): \Sulu\Bundle\DocumentManagerBundle\Command\InitializeCommand => ($container->privates['sulu_document_manager.command.initialize'] ?? $container->load('getSuluDocumentManager_Command_InitializeService')));
    }
}
