<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluPage_Command_ValidateWebspaces_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_page.command.validate_webspaces.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_page.command.validate_webspaces.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:content:validate:webspaces', [], 'Dumps webspaces and will show an error when template could not be loaded', false, #[\Closure(name: 'sulu_page.command.validate_webspaces', class: 'Sulu\\Bundle\\PageBundle\\Command\\ValidateWebspacesCommand')] fn (): \Sulu\Bundle\PageBundle\Command\ValidateWebspacesCommand => ($container->privates['sulu_page.command.validate_webspaces'] ?? $container->load('getSuluPage_Command_ValidateWebspacesService')));
    }
}
