<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluDocumentManager_Command_FixturesLoad_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_document_manager.command.fixtures_load.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_document_manager.command.fixtures_load.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:document:fixtures:load', [], 'Loads data fixtures services tagged with "sulu.document_manager_fixture".', false, #[\Closure(name: 'sulu_document_manager.command.fixtures_load', class: 'Sulu\\Bundle\\DocumentManagerBundle\\Command\\FixturesLoadCommand')] fn (): \Sulu\Bundle\DocumentManagerBundle\Command\FixturesLoadCommand => ($container->privates['sulu_document_manager.command.fixtures_load'] ?? $container->load('getSuluDocumentManager_Command_FixturesLoadService')));
    }
}
