<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluPage_Command_MaintainResourceLocator_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_page.command.maintain_resource_locator.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_page.command.maintain_resource_locator.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:content:resource-locator:maintain', [], 'Resets the cached url value on every node in the live workspace', false, #[\Closure(name: 'sulu_page.command.maintain_resource_locator', class: 'Sulu\\Bundle\\PageBundle\\Command\\MaintainResourceLocatorCommand')] fn (): \Sulu\Bundle\PageBundle\Command\MaintainResourceLocatorCommand => ($container->privates['sulu_page.command.maintain_resource_locator'] ?? $container->load('getSuluPage_Command_MaintainResourceLocatorService')));
    }
}
