<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluSnippet_Command_Export_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_snippet.command.export.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_snippet.command.export.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:snippet:export', [], 'Export snippet translations from given language into xliff file for translating into a new language.', false, #[\Closure(name: 'sulu_snippet.command.export', class: 'Sulu\\Bundle\\SnippetBundle\\Command\\SnippetExportCommand')] fn (): \Sulu\Bundle\SnippetBundle\Command\SnippetExportCommand => ($container->privates['sulu_snippet.command.export'] ?? $container->load('getSuluSnippet_Command_ExportService')));
    }
}
