<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluPage_Command_CopyLocale_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_page.command.copy_locale.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_page.command.copy_locale.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:content:locale-copy', [], 'Copy content nodes from one locale to another', false, #[\Closure(name: 'sulu_page.command.copy_locale', class: 'Sulu\\Bundle\\PageBundle\\Command\\ContentLocaleCopyCommand')] fn (): \Sulu\Bundle\PageBundle\Command\ContentLocaleCopyCommand => ($container->privates['sulu_page.command.copy_locale'] ?? $container->load('getSuluPage_Command_CopyLocaleService')));
    }
}
