<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluDocumentManager_Command_SubscriberDebug_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_document_manager.command.subscriber_debug.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_document_manager.command.subscriber_debug.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:document:subscriber:debug', [], 'Show event listeners associated with the document manager', false, #[\Closure(name: 'sulu_document_manager.command.subscriber_debug', class: 'Sulu\\Bundle\\DocumentManagerBundle\\Command\\SubscriberDebugCommand')] fn (): \Sulu\Bundle\DocumentManagerBundle\Command\SubscriberDebugCommand => ($container->privates['sulu_document_manager.command.subscriber_debug'] ?? $container->load('getSuluDocumentManager_Command_SubscriberDebugService')));
    }
}
