<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluPage_Command_WebspaceImport_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_page.command.webspace_import.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_page.command.webspace_import.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:webspaces:import', [], 'Import webspace page translations from xliff file into a specific language.', false, #[\Closure(name: 'sulu_page.command.webspace_import', class: 'Sulu\\Bundle\\PageBundle\\Command\\WebspaceImportCommand')] fn (): \Sulu\Bundle\PageBundle\Command\WebspaceImportCommand => ($container->privates['sulu_page.command.webspace_import'] ?? $container->load('getSuluPage_Command_WebspaceImportService')));
    }
}
