<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SuluPage_Command_ValidatePages_LazyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.sulu_page.command.validate_pages.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.sulu_page.command.validate_pages.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('sulu:content:validate', [], 'Dumps pages without valid templates', false, #[\Closure(name: 'sulu_page.command.validate_pages', class: 'Sulu\\Bundle\\PageBundle\\Command\\ValidatePagesCommand')] fn (): \Sulu\Bundle\PageBundle\Command\ValidatePagesCommand => ($container->privates['sulu_page.command.validate_pages'] ?? $container->load('getSuluPage_Command_ValidatePagesService')));
    }
}
