<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssets_PackagesService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'assets.packages' shared service.
     *
     * @return \Symfony\Component\Asset\Packages
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['assets.packages'] = new \Symfony\Component\Asset\Packages(($container->privates['assets._default_package'] ?? $container->load('getAssets_DefaultPackageService')), new RewindableGenerator(function () use ($container) {
            yield 'sulu_admin' => ($container->privates['assets._package_sulu_admin'] ?? $container->load('getAssets_PackageSuluAdminService'));
        }, 1));
    }
}
