<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_HandcraftedinthealpsRestRouting_CommandService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.handcraftedinthealps_rest_routing.command' shared service.
     *
     * @return \HandcraftedInTheAlps\RestRoutingBundle\Command\DumpRoutes
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.handcraftedinthealps_rest_routing.command'] = new \HandcraftedInTheAlps\RestRoutingBundle\Command\DumpRoutes(($container->services['router'] ?? self::getRouterService($container)));
    }
}
