<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryConverterService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sulu\Bundle\CategoryBundle\Search\Converter\CategoryConverter' shared service.
     *
     * @return \Sulu\Bundle\CategoryBundle\Search\Converter\CategoryConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_category.category_manager'] ?? $container->load('getSuluCategory_CategoryManagerService'));

        if (isset($container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'])) {
            return $container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'];
        }
        $b = ($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService'));

        if (isset($container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'])) {
            return $container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'];
        }
        $c = ($container->privates['massive_search.object_to_document_converter'] ?? $container->load('getMassiveSearch_ObjectToDocumentConverterService'));

        if (isset($container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'])) {
            return $container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'];
        }
        $d = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'])) {
            return $container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'];
        }

        return $container->privates['Sulu\\Bundle\\CategoryBundle\\Search\\Converter\\CategoryConverter'] = new \Sulu\Bundle\CategoryBundle\Search\Converter\CategoryConverter($a, $b, $c, $d);
    }
}
