<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_MassiveSearch_Command_ReindexService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.massive_search.command.reindex' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Command\ReindexCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.massive_search.command.reindex'] = new \Massive\Bundle\SearchBundle\Command\ReindexCommand(($container->privates['massive_search.reindex.resume_manager'] ??= new \Massive\Bundle\SearchBundle\Search\Reindex\ResumeManager()), ($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService')), ($container->privates['massive_search.reindex.provider_registry'] ?? $container->load('getMassiveSearch_Reindex_ProviderRegistryService')), 'dev');
    }
}
