<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDtlContent_Form_Type_PageService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'dtl_content.form.type.page' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Form\Type\PageDocumentType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['dtl_content.form.type.page'])) {
            return $container->privates['dtl_content.form.type.page'];
        }
        $b = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->privates['dtl_content.form.type.page'])) {
            return $container->privates['dtl_content.form.type.page'];
        }
        $c = ($container->privates['sulu_document_manager.metadata_factory'] ?? self::getSuluDocumentManager_MetadataFactoryService($container));

        if (isset($container->privates['dtl_content.form.type.page'])) {
            return $container->privates['dtl_content.form.type.page'];
        }

        return $container->privates['dtl_content.form.type.page'] = new \Sulu\Bundle\PageBundle\Form\Type\PageDocumentType($a, $b, $c);
    }
}
