<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDtlContent_Form_Type_HomeService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'dtl_content.form.type.home' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Form\Type\HomeDocumentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['dtl_content.form.type.home'] = new \Sulu\Bundle\PageBundle\Form\Type\HomeDocumentType();
    }
}
