<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_phpcr.jackalope_doctrine_dbal.schema' shared service.
     *
     * @return \Jackalope\Transport\DoctrineDBAL\RepositorySchema
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema'] = $container->createProxy('RepositorySchemaGhostB7af69e', static fn () => \RepositorySchemaGhostB7af69e::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        return ($lazyLoad->__construct([], ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container))) && false ?: $lazyLoad);
    }
}
