<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaListenerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine_phpcr.jackalope_doctrine_dbal.schema_listener' shared service.
     *
     * @return \Doctrine\Bundle\PHPCRBundle\EventListener\JackalopeDoctrineDbalSchemaListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema'] ?? $container->load('getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService'));

        if (isset($container->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema_listener'])) {
            return $container->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema_listener'];
        }

        return $container->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema_listener'] = new \Doctrine\Bundle\PHPCRBundle\EventListener\JackalopeDoctrineDbalSchemaListener($a);
    }
}
