<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.extension'] ?? $container->load('getForm_ExtensionService'));

        if (isset($container->privates['form.registry'])) {
            return $container->privates['form.registry'];
        }

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([$a], ($container->privates['form.resolved_type_factory'] ??= new \Symfony\Component\Form\ResolvedFormTypeFactory()));
    }
}
