<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_Type_Phpcr_ReferenceService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.type.phpcr.reference' shared service.
     *
     * @return \Doctrine\Bundle\PHPCRBundle\Form\Type\PHPCRReferenceType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container));

        if (isset($container->privates['form.type.phpcr.reference'])) {
            return $container->privates['form.type.phpcr.reference'];
        }

        return $container->privates['form.type.phpcr.reference'] = new \Doctrine\Bundle\PHPCRBundle\Form\Type\PHPCRReferenceType($a);
    }
}
