<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandcraftedinthealpsRestRouting_Loader_Reader_ActionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'handcraftedinthealps_rest_routing.loader.reader.action' shared service.
     *
     * @return \HandcraftedInTheAlps\RestRoutingBundle\Routing\Loader\Reader\RestActionReader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['handcraftedinthealps_rest_routing.loader.reader.action'] = new \HandcraftedInTheAlps\RestRoutingBundle\Routing\Loader\Reader\RestActionReader(($container->privates['handcraftedinthealps_rest_routing.annotation_reader'] ?? $container->load('getHandcraftedinthealpsRestRouting_AnnotationReaderService')), ($container->privates['fos_rest.request.param_fetcher.reader'] ??= new \FOS\RestBundle\Request\ParamReader(NULL)), ($container->privates['handcraftedinthealps_rest_routing.inflector.doctrine'] ??= new \HandcraftedInTheAlps\RestRoutingBundle\Inflector\DoctrineInflector()), true, ['json' => true, 'csv' => true], true);
    }
}
