<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_HandlerRegistry_ServiceLocatorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'jms_serializer.handler_registry.service_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['jms_serializer.handler_registry.service_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sulu_core.rest.datetime_handler' => ['privates', 'sulu_core.rest.datetime_handler', 'getSuluCore_Rest_DatetimeHandlerService', true],
            'jms_serializer.datetime_handler' => ['privates', 'jms_serializer.datetime_handler', 'getJmsSerializer_DatetimeHandlerService', true],
            'jms_serializer.union_handler' => ['privates', 'jms_serializer.union_handler', 'getJmsSerializer_UnionHandlerService', true],
            'jms_serializer.array_collection_handler' => ['privates', 'jms_serializer.array_collection_handler', 'getJmsSerializer_ArrayCollectionHandlerService', true],
            'jms_serializer.iterator_handler' => ['privates', 'jms_serializer.iterator_handler', 'getJmsSerializer_IteratorHandlerService', true],
            'sulu_page.document.serializer.handler.structure' => ['privates', 'sulu_page.document.serializer.handler.structure', 'getSuluPage_Document_Serializer_Handler_StructureService', true],
            'sulu_page.document.serializer.handler.extension_container' => ['privates', 'sulu_page.document.serializer.handler.extension_container', 'getSuluPage_Document_Serializer_Handler_ExtensionContainerService', true],
            'sulu_page.compat.serializer.handler.page_bridge' => ['privates', 'sulu_page.compat.serializer.handler.page_bridge', 'getSuluPage_Compat_Serializer_Handler_PageBridgeService', true],
            'jms_serializer.constraint_violation_handler' => ['privates', 'jms_serializer.constraint_violation_handler', 'getJmsSerializer_ConstraintViolationHandlerService', true],
            'fos_rest.serializer.flatten_exception_handler' => ['privates', 'fos_rest.serializer.flatten_exception_handler', 'getFosRest_Serializer_FlattenExceptionHandlerService', true],
            'sulu_admin.schema_handler' => ['privates', 'sulu_admin.schema_handler', 'getSuluAdmin_SchemaHandlerService', true],
            'sulu_document_manager.serializer.handler.children_collection' => ['privates', 'sulu_document_manager.serializer.handler.children_collection', 'getSuluDocumentManager_Serializer_Handler_ChildrenCollectionService', true],
            'fos_rest.serializer.form_error_handler' => ['privates', 'fos_rest.serializer.form_error_handler', 'getFosRest_Serializer_FormErrorHandlerService', true],
        ], [
            'sulu_core.rest.datetime_handler' => '?',
            'jms_serializer.datetime_handler' => '?',
            'jms_serializer.union_handler' => '?',
            'jms_serializer.array_collection_handler' => '?',
            'jms_serializer.iterator_handler' => '?',
            'sulu_page.document.serializer.handler.structure' => '?',
            'sulu_page.document.serializer.handler.extension_container' => '?',
            'sulu_page.compat.serializer.handler.page_bridge' => '?',
            'jms_serializer.constraint_violation_handler' => '?',
            'fos_rest.serializer.flatten_exception_handler' => '?',
            'sulu_admin.schema_handler' => '?',
            'sulu_document_manager.serializer.handler.children_collection' => '?',
            'fos_rest.serializer.form_error_handler' => '?',
        ]);
    }
}
