<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_TraceableHandlerRegistry_InnerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'jms_serializer.traceable_handler_registry.inner' shared service.
     *
     * @return \JMS\Serializer\Handler\LazyHandlerRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['jms_serializer.handler_registry.service_locator'] ?? $container->load('getJmsSerializer_HandlerRegistry_ServiceLocatorService'));

        if (isset($container->privates['jms_serializer.traceable_handler_registry.inner'])) {
            return $container->privates['jms_serializer.traceable_handler_registry.inner'];
        }

        return $container->privates['jms_serializer.traceable_handler_registry.inner'] = new \JMS\Serializer\Handler\LazyHandlerRegistry($a);
    }
}
