<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_DoctrineObjectConstructor_InnerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'jms_serializer.doctrine_object_constructor.inner' shared service.
     *
     * @return \JMS\Serializer\Construction\UnserializeObjectConstructor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['jms_serializer.doctrine_object_constructor.inner'] = new \JMS\Serializer\Construction\UnserializeObjectConstructor();
    }
}
