<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_Events_DeindexListenerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_search.events.deindex_listener' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\EventListener\DeindexListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService'));

        if (isset($container->privates['massive_search.events.deindex_listener'])) {
            return $container->privates['massive_search.events.deindex_listener'];
        }

        return $container->privates['massive_search.events.deindex_listener'] = new \Massive\Bundle\SearchBundle\Search\EventListener\DeindexListener($a);
    }
}
