<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveBuild_Builder_Virtual_DevService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_build.builder.virtual.dev' shared service.
     *
     * @return \Massive\Bundle\BuildBundle\Builder\VirtualBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['massive_build.builder.virtual.dev'] = new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('dev', ['database', 'fixtures', 'phpcr', 'user', 'phpcr_migrations', 'system_collections', 'security', 'search_init']);
    }
}
