<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveSearch_Search_EventSubscriber_PurgeSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_search.search.event_subscriber.purge_subscriber' shared service.
     *
     * @return \Massive\Bundle\SearchBundle\Search\EventSubscriber\PurgeSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService'));

        if (isset($container->privates['massive_search.search.event_subscriber.purge_subscriber'])) {
            return $container->privates['massive_search.search.event_subscriber.purge_subscriber'];
        }

        return $container->privates['massive_search.search.event_subscriber.purge_subscriber'] = new \Massive\Bundle\SearchBundle\Search\EventSubscriber\PurgeSubscriber($a);
    }
}
