<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveBuild_Builder_Virtual_ProdService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_build.builder.virtual.prod' shared service.
     *
     * @return \Massive\Bundle\BuildBundle\Builder\VirtualBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['massive_build.builder.virtual.prod'] = new \Massive\Bundle\BuildBundle\Builder\VirtualBuilder('prod', ['database', 'phpcr', 'fixtures', 'phpcr_migrations', 'system_collections', 'security']);
    }
}
