<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMassiveBuild_Command_BuildService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'massive_build.command.build' shared service.
     *
     * @return \Sulu\Bundle\CoreBundle\CommandOptional\SuluBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['massive_build.command.build'] = $instance = new \Sulu\Bundle\CoreBundle\CommandOptional\SuluBuildCommand(($container->privates['massive_build.build.registry'] ?? $container->load('getMassiveBuild_Build_RegistryService')), $container);

        $instance->setName('sulu:build');

        return $instance;
    }
}
