<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerspeqtiveSuluSnippetTabs_Extension_EventsService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'perspeqtive_sulu_snippet_tabs.extension.events' shared service.
     *
     * @return \PERSPEQTIVE\SuluSnippetTabsBundle\Extension\SnippetTabExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_admin.form_metadata.form_xml_loader'] ?? $container->load('getSuluAdmin_FormMetadata_FormXmlLoaderService'));

        if (isset($container->privates['perspeqtive_sulu_snippet_tabs.extension.events'])) {
            return $container->privates['perspeqtive_sulu_snippet_tabs.extension.events'];
        }

        return $container->privates['perspeqtive_sulu_snippet_tabs.extension.events'] = new \PERSPEQTIVE\SuluSnippetTabsBundle\Extension\SnippetTabExtension(new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\XmlFormMetadataLoader($a, ($container->privates['sulu_admin.field_metadata_validator.chain'] ?? $container->load('getSuluAdmin_FieldMetadataValidator_ChainService')), $container->parameters['sulu_admin.forms.directories'], ($container->targetDir.''.'/sulu/forms'), true), 'events', ['events_locations', 'events_catering']);
    }
}
