<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRepositoryInitCommandService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Doctrine\Bundle\PHPCRBundle\Command\RepositoryInitCommand' shared service.
     *
     * @return \Doctrine\Bundle\PHPCRBundle\Command\RepositoryInitCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.Doctrine\\Bundle\\PHPCRBundle\\Command\\RepositoryInitCommand'] = new \Doctrine\Bundle\PHPCRBundle\Command\RepositoryInitCommand(($container->services['doctrine_phpcr.initializer_manager'] ?? $container->load('getDoctrinePhpcr_InitializerManagerService')));
    }
}
