<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_EventSubscriber_CacheClearService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_website.event_subscriber.cache_clear' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\EventSubscriber\DomainEventEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_activity.domain_event_dispatcher'] ?? self::getSuluActivity_DomainEventDispatcherService($container));

        if (isset($container->privates['sulu_website.event_subscriber.cache_clear'])) {
            return $container->privates['sulu_website.event_subscriber.cache_clear'];
        }

        return $container->privates['sulu_website.event_subscriber.cache_clear'] = new \Sulu\Bundle\WebsiteBundle\EventSubscriber\DomainEventEventSubscriber($a, ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)));
    }
}
