<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_EncoderFactoryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_security.encoder_factory' shared service.
     *
     * @return \Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.encoder_factory'] = new \Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory(['Sulu\\Bundle\\SecurityBundle\\Entity\\User' => ['class' => 'Symfony\\Component\\PasswordHasher\\Hasher\\PlaintextPasswordHasher', 'arguments' => [false]]]);
    }
}
