<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Search_Metadata_Provider_StructureService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.search.metadata.provider.structure' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Search\Metadata\StructureProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.metadata_factory'] ?? self::getSuluDocumentManager_MetadataFactoryService($container));

        if (isset($container->privates['sulu_page.search.metadata.provider.structure'])) {
            return $container->privates['sulu_page.search.metadata.provider.structure'];
        }
        $b = ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService'));

        if (isset($container->privates['sulu_page.search.metadata.provider.structure'])) {
            return $container->privates['sulu_page.search.metadata.provider.structure'];
        }

        return $container->privates['sulu_page.search.metadata.provider.structure'] = new \Sulu\Bundle\PageBundle\Search\Metadata\StructureProvider(($container->privates['sulu_search.search.factory'] ??= new \Sulu\Bundle\SearchBundle\Search\Factory()), $a, ($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)), $b, $container->parameters['sulu_page.search.mapping']);
    }
}
