<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_PreviewLinkControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_preview.preview_link_controller' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\UserInterface\Controller\PreviewLinkController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_preview.preview_link_controller'] = new \Sulu\Bundle\PreviewBundle\UserInterface\Controller\PreviewLinkController(($container->privates['sulu_preview.preview_link_repository'] ?? $container->load('getSuluPreview_PreviewLinkRepositoryService')), ($container->privates['sulu_preview.preview_link_manager'] ?? $container->load('getSuluPreview_PreviewLinkManagerService')), ($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
