<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Command_CleanupHistoryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.command.cleanup_history' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Command\CleanupHistoryCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_page.command.cleanup_history'] = $instance = new \Sulu\Bundle\PageBundle\Command\CleanupHistoryCommand(($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container)), ($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container)), ($container->services['sulu_document_manager.live_session'] ?? $container->load('getSuluDocumentManager_LiveSessionService')));

        $instance->setName('sulu:content:cleanup-history');
        $instance->setDescription('Cleanup resource-locator history');

        return $instance;
    }
}
