<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Suscriber_Behavior_ParentService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.suscriber.behavior.parent' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\ParentSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.proxy_factory'] ?? self::getSuluDocumentManager_ProxyFactoryService($container));

        if (isset($container->privates['sulu_document_manager.suscriber.behavior.parent'])) {
            return $container->privates['sulu_document_manager.suscriber.behavior.parent'];
        }
        $b = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_document_manager.suscriber.behavior.parent'])) {
            return $container->privates['sulu_document_manager.suscriber.behavior.parent'];
        }
        $c = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->privates['sulu_document_manager.suscriber.behavior.parent'])) {
            return $container->privates['sulu_document_manager.suscriber.behavior.parent'];
        }

        return $container->privates['sulu_document_manager.suscriber.behavior.parent'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\ParentSubscriber($a, $b, $c);
    }
}
