<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_RoleControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_security.role_controller' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Controller\RoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.role_controller'] = new \Sulu\Bundle\SecurityBundle\Controller\RoleController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['sulu_security.mask_converter'] ?? self::getSuluSecurity_MaskConverterService($container)), ($container->services['sulu.repository.role'] ?? self::getSulu_Repository_RoleService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_activity.domain_event_collector'] ?? self::getSuluActivity_DomainEventCollectorService($container)), 'Sulu\\Bundle\\SecurityBundle\\Entity\\Role');
    }
}
