<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_ReferenceStore_SnippetAreaService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.reference_store.snippet_area' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.reference_store.snippet_area'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore();
    }
}
