<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_FormMetadata_FormXmlLoaderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_admin.form_metadata.form_xml_loader' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\FormMetadata\FormXmlLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_admin.form_metadata.form_metadata_mapper'] ?? $container->load('getSuluAdmin_FormMetadata_FormMetadataMapperService'));

        if (isset($container->privates['sulu_admin.form_metadata.form_xml_loader'])) {
            return $container->privates['sulu_admin.form_metadata.form_xml_loader'];
        }

        return $container->privates['sulu_admin.form_metadata.form_xml_loader'] = new \Sulu\Bundle\AdminBundle\FormMetadata\FormXmlLoader(($container->privates['sulu_page.structure.properties_xml_parser'] ?? self::getSuluPage_Structure_PropertiesXmlParserService($container)), ($container->privates['sulu_page.structure.schema_xml_parser'] ??= new \Sulu\Component\Content\Metadata\Parser\SchemaXmlParser()), $container->parameters['sulu_core.locales'], $a);
    }
}
