<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_SmartContentItemControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.smart_content_item_controller' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Controller\SmartContentItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.smart_content_item_controller'] = new \Sulu\Bundle\PageBundle\Controller\SmartContentItemController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_tag.tag_manager'] ?? self::getSuluTag_TagManagerService($container)), ($container->services['sulu_page.smart_content.data_provider_pool'] ?? $container->load('getSuluPage_SmartContent_DataProviderPoolService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
