<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_TeaserControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.teaser_controller' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Controller\TeaserController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.teaser_controller'] = new \Sulu\Bundle\PageBundle\Controller\TeaserController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['sulu_page.teaser.manager'] ?? $container->load('getSuluPage_Teaser_ManagerService')));
    }
}
