<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_ChainGeneratorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_route.chain_generator' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Generator\ChainRouteGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.repository.route'] ?? $container->load('getSulu_Repository_RouteService'));

        if (isset($container->privates['sulu_route.chain_generator'])) {
            return $container->privates['sulu_route.chain_generator'];
        }

        return $container->privates['sulu_route.chain_generator'] = new \Sulu\Bundle\RouteBundle\Generator\ChainRouteGenerator([], [], $a);
    }
}
