<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_Subscriber_PageTreeRouteService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_route.subscriber.page_tree_route' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Document\Subscriber\PageTreeRouteSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->privates['sulu_route.subscriber.page_tree_route'])) {
            return $container->privates['sulu_route.subscriber.page_tree_route'];
        }
        $b = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_route.subscriber.page_tree_route'])) {
            return $container->privates['sulu_route.subscriber.page_tree_route'];
        }
        $c = ($container->services['sulu_document_manager.live_session'] ?? $container->load('getSuluDocumentManager_LiveSessionService'));

        if (isset($container->privates['sulu_route.subscriber.page_tree_route'])) {
            return $container->privates['sulu_route.subscriber.page_tree_route'];
        }
        $d = ($container->privates['sulu_route.page_tree_route.updater.request'] ?? $container->load('getSuluRoute_PageTreeRoute_Updater_RequestService'));

        if (isset($container->privates['sulu_route.subscriber.page_tree_route'])) {
            return $container->privates['sulu_route.subscriber.page_tree_route'];
        }

        return $container->privates['sulu_route.subscriber.page_tree_route'] = new \Sulu\Bundle\RouteBundle\Document\Subscriber\PageTreeRouteSubscriber($a, ($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)), $b, ($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)), $c, $d);
    }
}
