<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_PageTreeRoute_Updater_RequestService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_route.page_tree_route.updater.request' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\PageTree\PageTreeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->privates['sulu_route.page_tree_route.updater.request'])) {
            return $container->privates['sulu_route.page_tree_route.updater.request'];
        }
        $b = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_route.page_tree_route.updater.request'])) {
            return $container->privates['sulu_route.page_tree_route.updater.request'];
        }

        return $container->privates['sulu_route.page_tree_route.updater.request'] = new \Sulu\Bundle\RouteBundle\PageTree\PageTreeRepository($a, ($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)), ($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)), $b);
    }
}
