<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Extension_SeoService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.extension.seo' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Content\Structure\SeoStructureExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.extension.seo'] = new \Sulu\Bundle\PageBundle\Content\Structure\SeoStructureExtension();
    }
}
