<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_FormatOptionsManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.format_options_manager' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\FormatOptions\FormatOptionsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.format_options_manager'] = new \Sulu\Bundle\MediaBundle\Media\FormatOptions\FormatOptionsManager(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_media.format_options_repository'] ?? $container->load('getSuluMedia_FormatOptionsRepositoryService')), ($container->services['sulu_media.media_manager'] ?? self::getSuluMedia_MediaManagerService($container)), ($container->services['sulu_media.format_manager'] ?? self::getSuluMedia_FormatManagerService($container)), ($container->privates['sulu_activity.domain_event_collector'] ?? self::getSuluActivity_DomainEventCollectorService($container)), $container->parameters['sulu_media.image.formats']);
    }
}
