<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_Command_UpdateRouteService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_route.command.update_route' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Command\UpdateRouteCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_route.command.update_route'] = $instance = new \Sulu\Bundle\RouteBundle\Command\UpdateRouteCommand(($container->services['translator'] ?? self::getTranslatorService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_route.manager.route_manager'] ?? $container->load('getSuluRoute_Manager_RouteManagerService')));

        $instance->setName('sulu:route:update');
        $instance->setDescription('Update the routes for all entities.');

        return $instance;
    }
}
