<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_DocumentDomainEventCollectorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.document_domain_event_collector' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Collector\DocumentDomainEventCollector
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_activity.domain_event_dispatcher'] ?? self::getSuluActivity_DomainEventDispatcherService($container));

        if (isset($container->privates['sulu_document_manager.document_domain_event_collector'])) {
            return $container->privates['sulu_document_manager.document_domain_event_collector'];
        }

        return $container->privates['sulu_document_manager.document_domain_event_collector'] = new \Sulu\Bundle\DocumentManagerBundle\Collector\DocumentDomainEventCollector($a);
    }
}
