<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Phpcr_FindService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.phpcr.find' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Phpcr\FindSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.metadata_factory'] ?? self::getSuluDocumentManager_MetadataFactoryService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.phpcr.find'])) {
            return $container->privates['sulu_document_manager.subscriber.phpcr.find'];
        }
        $b = ($container->privates['sulu_document_manager.event_dispatcher.standard'] ?? self::getSuluDocumentManager_EventDispatcher_StandardService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.phpcr.find'])) {
            return $container->privates['sulu_document_manager.subscriber.phpcr.find'];
        }

        return $container->privates['sulu_document_manager.subscriber.phpcr.find'] = new \Sulu\Component\DocumentManager\Subscriber\Phpcr\FindSubscriber($a, ($container->privates['sulu_document_manager.node_manager'] ?? self::getSuluDocumentManager_NodeManagerService($container)), $b);
    }
}
