<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Teaser_Provider_PhpcrService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.teaser.provider.phpcr' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Teaser\PHPCRPageTeaserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu.content.query_executor'] ?? $container->load('getSulu_Content_QueryExecutorService'));

        if (isset($container->privates['sulu_page.teaser.provider.phpcr'])) {
            return $container->privates['sulu_page.teaser.provider.phpcr'];
        }
        $b = ($container->privates['sulu_page.smart_content.data_provider.content.query_builder'] ?? $container->load('getSuluPage_SmartContent_DataProvider_Content_QueryBuilderService'));

        if (isset($container->privates['sulu_page.teaser.provider.phpcr'])) {
            return $container->privates['sulu_page.teaser.provider.phpcr'];
        }

        return $container->privates['sulu_page.teaser.provider.phpcr'] = new \Sulu\Bundle\PageBundle\Teaser\PHPCRPageTeaserProvider($a, $b, ($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)), true, $container->parameters['sulu_security.permissions']);
    }
}
