<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Preview_DefaultsProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.preview.defaults_provider' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Preview\PageRouteDefaultsProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.preview.defaults_provider'] = new \Sulu\Bundle\PageBundle\Preview\PageRouteDefaultsProvider(($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)), ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container)), ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)));
    }
}
