<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_SnippetTrashSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.snippet_trash_subscriber' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\EventListener\SnippetTrashSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_snippet.snippet_trash_subscriber'])) {
            return $container->privates['sulu_snippet.snippet_trash_subscriber'];
        }

        return $container->privates['sulu_snippet.snippet_trash_subscriber'] = new \Sulu\Bundle\SnippetBundle\EventListener\SnippetTrashSubscriber(($container->privates['sulu_trash.trash_manager'] ?? self::getSuluTrash_TrashManagerService($container)), $a);
    }
}
