<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Behavior_AutoNameService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.behavior.auto_name' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Behavior\Path\AutoNameSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.live_session'] ?? $container->load('getSuluDocumentManager_LiveSessionService'));

        if (isset($container->privates['sulu_document_manager.subscriber.behavior.auto_name'])) {
            return $container->privates['sulu_document_manager.subscriber.behavior.auto_name'];
        }
        $b = ($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.behavior.auto_name'])) {
            return $container->privates['sulu_document_manager.subscriber.behavior.auto_name'];
        }

        return $container->privates['sulu_document_manager.subscriber.behavior.auto_name'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Path\AutoNameSubscriber(($container->privates['sulu_document_manager.document_registry'] ??= new \Sulu\Component\DocumentManager\DocumentRegistry('en')), ($container->privates['sulu_document_manager.node_name_slugifier'] ?? $container->load('getSuluDocumentManager_NodeNameSlugifierService')), ($container->privates['sulu_document_manager.name_resolver'] ??= new \Sulu\Component\DocumentManager\NameResolver()), ($container->privates['sulu_document_manager.node_manager'] ?? self::getSuluDocumentManager_NodeManagerService($container)), $a, $b);
    }
}
