<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Twig_ContentPathService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_website.twig.content_path' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Twig\Content\ContentPathTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_website.twig.content_path'] = new \Sulu\Bundle\WebsiteBundle\Twig\Content\ContentPathTwigExtension(($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), 'dev', ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)));
    }
}
