<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_Rules_DeviceService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_audience_targeting.rules.device' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Rule\DeviceTypeRule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_audience_targeting.rules.device'] = new \Sulu\Bundle\AudienceTargetingBundle\Rule\DeviceTypeRule(($container->privates['sulu_audience_targeting.device_detector'] ?? $container->load('getSuluAudienceTargeting_DeviceDetectorService')), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
