<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_MovePageTreeCommandService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_route.move_page_tree_command' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Command\MovePageTreeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_route.move_page_tree_command'] = $instance = new \Sulu\Bundle\RouteBundle\Command\MovePageTreeCommand(($container->privates['sulu_route.page_tree_route.mover'] ?? $container->load('getSuluRoute_PageTreeRoute_MoverService')), ($container->privates['sulu.content.resource_locator.strategy_pool'] ?? $container->load('getSulu_Content_ResourceLocator_StrategyPoolService')), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)));

        $instance->setName('sulu:route:page-tree:move');

        return $instance;
    }
}
