<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Command_ValidateWebspacesService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.command.validate_webspaces' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Command\ValidateWebspacesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_page.command.validate_webspaces'] = $instance = new \Sulu\Bundle\PageBundle\Command\ValidateWebspacesCommand(($container->privates['twig'] ?? $container->load('getTwigService')), ($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)), NULL, ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), ($container->services['sulu.content.webspace_structure_provider'] ?? $container->load('getSulu_Content_WebspaceStructureProviderService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setName('sulu:content:validate:webspaces');
        $instance->setDescription('Dumps webspaces and will show an error when template could not be loaded');

        return $instance;
    }
}
