<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Resolver_TemplateAttributeService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_website.resolver.template_attribute' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Resolver\TemplateAttributeResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_website.resolver.template_attribute'] = new \Sulu\Bundle\WebsiteBundle\Resolver\TemplateAttributeResolver(($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), ($container->privates['sulu_website.resolver.request_analyzer'] ?? $container->load('getSuluWebsite_Resolver_RequestAnalyzerService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), 'dev', $container->parameters['sulu_website.enabled_twig_attributes']);
    }
}
