<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Import_WebspaceService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.import.webspace' shared service.
     *
     * @return \Sulu\Component\Content\Import\WebspaceImport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.import.webspace'] = new \Sulu\Component\Content\Import\WebspaceImport(($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container)), ($container->privates['sulu_document_manager.document_registry'] ??= new \Sulu\Component\DocumentManager\DocumentRegistry('en')), ($container->services['sulu_page.compat.structure.legacy_property_factory'] ?? self::getSuluPage_Compat_Structure_LegacyPropertyFactoryService($container)), ($container->privates['sulu.content.resource_locator.strategy.tree_leaf_edit'] ?? $container->load('getSulu_Content_ResourceLocator_Strategy_TreeLeafEditService')), ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService')), ($container->privates['sulu_page.import.manager'] ?? $container->load('getSuluPage_Import_ManagerService')), ($container->privates['sulu_page.import.webspace.xliff12'] ??= new \Sulu\Component\Import\Format\Xliff12()), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
