<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_CreateTrashItemSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.create_trash_item_subscriber' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\EventListener\PageTrashSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_page.create_trash_item_subscriber'])) {
            return $container->privates['sulu_page.create_trash_item_subscriber'];
        }

        return $container->privates['sulu_page.create_trash_item_subscriber'] = new \Sulu\Bundle\PageBundle\EventListener\PageTrashSubscriber(($container->privates['sulu_trash.trash_manager'] ?? self::getSuluTrash_TrashManagerService($container)), $a);
    }
}
