<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_WebspaceLocalizationControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.webspace_localization_controller' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Controller\WebspaceLocalizationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.webspace_localization_controller'] = new \Sulu\Bundle\PageBundle\Controller\WebspaceLocalizationController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)));
    }
}
