<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_ContentType_PageTreeRouteService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_route.content_type.page_tree_route' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Content\Type\PageTreeRouteContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->services['sulu_route.content_type.page_tree_route'])) {
            return $container->services['sulu_route.content_type.page_tree_route'];
        }
        $b = ($container->privates['sulu_route.chain_generator'] ?? $container->load('getSuluRoute_ChainGeneratorService'));

        if (isset($container->services['sulu_route.content_type.page_tree_route'])) {
            return $container->services['sulu_route.content_type.page_tree_route'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sulu_route.content_type.page_tree_route'])) {
            return $container->services['sulu_route.content_type.page_tree_route'];
        }

        return $container->services['sulu_route.content_type.page_tree_route'] = new \Sulu\Bundle\RouteBundle\Content\Type\PageTreeRouteContentType($a, ($container->privates['sulu_document_manager.document_registry'] ??= new \Sulu\Component\DocumentManager\DocumentRegistry('en')), $b, ($container->privates['sulu_route.manager.conflict_resolver.auto_increment'] ?? $container->load('getSuluRoute_Manager_ConflictResolver_AutoIncrementService')), $c);
    }
}
