<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_PermissionListenerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.permission_listener' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Search\EventListener\PermissionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_media.file_version_meta_repository'] ?? $container->load('getSuluMedia_FileVersionMetaRepositoryService'));

        if (isset($container->privates['sulu_media.permission_listener'])) {
            return $container->privates['sulu_media.permission_listener'];
        }
        $b = ($container->services['massive_search.search_manager'] ?? $container->load('getMassiveSearch_SearchManagerService'));

        if (isset($container->privates['sulu_media.permission_listener'])) {
            return $container->privates['sulu_media.permission_listener'];
        }

        return $container->privates['sulu_media.permission_listener'] = new \Sulu\Bundle\MediaBundle\Search\EventListener\PermissionListener($a, $b);
    }
}
