<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_WebspaceSelectHelperService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_audience_targeting.webspace_select_helper' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Admin\Helper\WebspaceSelect
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_audience_targeting.webspace_select_helper'] = new \Sulu\Bundle\AudienceTargetingBundle\Admin\Helper\WebspaceSelect(($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)));
    }
}
