<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_WebspaceStructureProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.content.webspace_structure_provider' shared service.
     *
     * @return \Sulu\Component\Webspace\StructureProvider\WebspaceStructureProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.webspace_structure_provider'] = new \Sulu\Component\Webspace\StructureProvider\WebspaceStructureProvider(($container->privates['twig'] ?? $container->load('getTwigService')), ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), ($container->privates['sulu.content.webspace_structure_provider.cache'] ?? $container->load('getSulu_Content_WebspaceStructureProvider_CacheService')));
    }
}
