<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_Twig_CacheService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_contact.twig.cache' shared service.
     *
     * @return \Doctrine\Common\Cache\Cache
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_contact.twig.cache'] = \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap(($container->privates['sulu_contact.twig.cache_adapter'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
    }
}
