<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Suscriber_Behavior_ChildrenService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.suscriber.behavior.children' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\ChildrenSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.proxy_factory'] ?? self::getSuluDocumentManager_ProxyFactoryService($container));

        if (isset($container->privates['sulu_document_manager.suscriber.behavior.children'])) {
            return $container->privates['sulu_document_manager.suscriber.behavior.children'];
        }

        return $container->privates['sulu_document_manager.suscriber.behavior.children'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\ChildrenSubscriber($a);
    }
}
