<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_ExpressionLanguageService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.expression_language' shared service.
     *
     * @return \Symfony\Component\ExpressionLanguage\ExpressionLanguage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.expression_language'] = new \Symfony\Component\ExpressionLanguage\ExpressionLanguage(NULL, [($container->privates['sulu_core.symfony_expression_language_provider'] ??= new \Sulu\Bundle\CoreBundle\ExpressionLanguage\ContainerExpressionLanguageProvider($container))]);
    }
}
