<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Compat_Serializer_Handler_PageBridgeService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.compat.serializer.handler.page_bridge' shared service.
     *
     * @return \Sulu\Component\Content\Compat\Serializer\PageBridgeHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_page.compat.serializer.handler.page_bridge'])) {
            return $container->privates['sulu_page.compat.serializer.handler.page_bridge'];
        }

        return $container->privates['sulu_page.compat.serializer.handler.page_bridge'] = new \Sulu\Component\Content\Compat\Serializer\PageBridgeHandler($a, ($container->services['sulu_page.compat.structure.legacy_property_factory'] ?? self::getSuluPage_Compat_Structure_LegacyPropertyFactoryService($container)), ($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)));
    }
}
