<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_EventSubscriber_InvalidationService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_custom_urls.event_subscriber.invalidation' shared service.
     *
     * @return \Sulu\Component\CustomUrl\Document\Subscriber\InvalidationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_custom_urls.manager'] ?? $container->load('getSuluCustomUrls_ManagerService'));

        if (isset($container->privates['sulu_custom_urls.event_subscriber.invalidation'])) {
            return $container->privates['sulu_custom_urls.event_subscriber.invalidation'];
        }
        $b = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_custom_urls.event_subscriber.invalidation'])) {
            return $container->privates['sulu_custom_urls.event_subscriber.invalidation'];
        }

        return $container->privates['sulu_custom_urls.event_subscriber.invalidation'] = new \Sulu\Component\CustomUrl\Document\Subscriber\InvalidationSubscriber($a, $b, NULL, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
