<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_FileVersionMetaRepositoryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.file_version_meta_repository' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Entity\FileVersionMetaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_media.file_version_meta_repository'])) {
            return $container->privates['sulu_media.file_version_meta_repository'];
        }

        return $container->privates['sulu_media.file_version_meta_repository'] = $a->getRepository('Sulu\\Bundle\\MediaBundle\\Entity\\FileVersionMeta');
    }
}
