<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaTrashItemHandlerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.media_trash_item_handler' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Trash\MediaTrashItemHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.repository.media'] ?? self::getSulu_Repository_MediaService($container));

        if (isset($container->privates['sulu_media.media_trash_item_handler'])) {
            return $container->privates['sulu_media.media_trash_item_handler'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_media.media_trash_item_handler'])) {
            return $container->privates['sulu_media.media_trash_item_handler'];
        }

        return $container->privates['sulu_media.media_trash_item_handler'] = new \Sulu\Bundle\MediaBundle\Trash\MediaTrashItemHandler(($container->privates['sulu_trash.trash_item_repository'] ?? self::getSuluTrash_TrashItemRepositoryService($container)), $a, $b, ($container->privates['sulu_trash.doctrine_restore_helper'] ?? $container->load('getSuluTrash_DoctrineRestoreHelperService')), ($container->privates['sulu_activity.domain_event_collector'] ?? self::getSuluActivity_DomainEventCollectorService($container)), ($container->services['sulu_media.storage'] ?? self::getSuluMedia_StorageService($container)));
    }
}
