<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Repository_AnalyticsService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.repository.analytics' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Entity\AnalyticsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['sulu.repository.analytics'] = $container->createProxy('AnalyticsRepositoryGhost40e2d7e', static fn () => \AnalyticsRepositoryGhost40e2d7e::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        return ($lazyLoad->__construct($a, $a->getClassMetadata('Sulu\\Bundle\\WebsiteBundle\\Entity\\Analytics')) && false ?: $lazyLoad);
    }
}
