<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Export_SnippetService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.export.snippet' shared service.
     *
     * @return \Sulu\Component\Snippet\Export\SnippetExport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.export.snippet'] = new \Sulu\Component\Snippet\Export\SnippetExport(($container->privates['twig'] ?? $container->load('getTwigService')), ($container->services['sulu_snippet.repository'] ?? $container->load('getSuluSnippet_RepositoryService')), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container)), ($container->privates['sulu_page.export.manager'] ?? $container->load('getSuluPage_Export_ManagerService')), $container->parameters['sulu_snippet.export.snippet.formats']);
    }
}
