<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Twig_SnippetService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.twig.snippet' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Twig\SnippetTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService'));

        if (isset($container->privates['sulu_snippet.twig.snippet'])) {
            return $container->privates['sulu_snippet.twig.snippet'];
        }
        $b = ($container->services['sulu_website.resolver.structure'] ?? $container->load('getSuluWebsite_Resolver_StructureService'));

        if (isset($container->privates['sulu_snippet.twig.snippet'])) {
            return $container->privates['sulu_snippet.twig.snippet'];
        }

        return $container->privates['sulu_snippet.twig.snippet'] = new \Sulu\Bundle\SnippetBundle\Twig\SnippetTwigExtension($a, ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), $b);
    }
}
