<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.page_controller' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Controller\PageController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_page.page_controller'] = new \Sulu\Bundle\PageBundle\Controller\PageController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService')), ($container->services['sulu_page.content_repository'] ?? self::getSuluPage_ContentRepositoryService($container)), ($container->services['sulu_hash.request_hash_checker'] ?? $container->load('getSuluHash_RequestHashCheckerService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container)), ($container->services['sulu_page.node_repository'] ?? $container->load('getSuluPage_NodeRepositoryService')), ($container->services['sulu_document_manager.metadata_factory.base'] ?? self::getSuluDocumentManager_MetadataFactory_BaseService($container)), ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')));
    }
}
