<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Command_ImportService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.command.import' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Command\SnippetImportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_snippet.command.import'] = $instance = new \Sulu\Bundle\SnippetBundle\Command\SnippetImportCommand(($container->services['sulu_snippet.import.snippet'] ?? $container->load('getSuluSnippet_Import_SnippetService')), ($container->privates['logger'] ?? self::getLoggerService($container)));

        $instance->setName('sulu:snippet:import');
        $instance->setDescription('Import snippet translations from xliff file into a specific language.');

        return $instance;
    }
}
