<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_ResourceLocator_StrategyPoolService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu.content.resource_locator.strategy_pool' shared service.
     *
     * @return \Sulu\Component\Content\Types\ResourceLocator\Strategy\ResourceLocatorStrategyPool
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu.content.resource_locator.strategy.tree_leaf_edit'] ?? $container->load('getSulu_Content_ResourceLocator_Strategy_TreeLeafEditService'));

        if (isset($container->privates['sulu.content.resource_locator.strategy_pool'])) {
            return $container->privates['sulu.content.resource_locator.strategy_pool'];
        }
        $b = ($container->privates['sulu.content.resource_locator.strategy.tree_full_edit'] ?? $container->load('getSulu_Content_ResourceLocator_Strategy_TreeFullEditService'));

        if (isset($container->privates['sulu.content.resource_locator.strategy_pool'])) {
            return $container->privates['sulu.content.resource_locator.strategy_pool'];
        }

        return $container->privates['sulu.content.resource_locator.strategy_pool'] = new \Sulu\Component\Content\Types\ResourceLocator\Strategy\ResourceLocatorStrategyPool(['tree_leaf_edit' => $a, 'tree_full_edit' => $b], ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)));
    }
}
