<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_UserManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_security.user_manager' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\UserManager\UserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['sulu_security.user_manager'])) {
            return $container->services['sulu_security.user_manager'];
        }
        $b = ($container->privates['sulu_security.group_repository'] ?? $container->load('getSuluSecurity_GroupRepositoryService'));

        if (isset($container->services['sulu_security.user_manager'])) {
            return $container->services['sulu_security.user_manager'];
        }
        $c = ($container->services['sulu_contact.contact_manager'] ?? $container->load('getSuluContact_ContactManagerService'));

        if (isset($container->services['sulu_security.user_manager'])) {
            return $container->services['sulu_security.user_manager'];
        }

        return $container->services['sulu_security.user_manager'] = new \Sulu\Bundle\SecurityBundle\UserManager\UserManager($a, ($container->services['sulu_security.encoder_factory'] ?? $container->load('getSuluSecurity_EncoderFactoryService')), ($container->services['sulu.repository.role'] ?? self::getSulu_Repository_RoleService($container)), $b, $c, ($container->services['sulu_security.salt_generator'] ??= new \Sulu\Component\Security\Authentication\SaltGenerator()), ($container->services['sulu.repository.user'] ?? self::getSulu_Repository_UserService($container)), ($container->privates['sulu_activity.domain_event_collector'] ?? self::getSuluActivity_DomainEventCollectorService($container)), NULL);
    }
}
