<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Import_SnippetService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.import.snippet' shared service.
     *
     * @return \Sulu\Component\Snippet\Import\SnippetImport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.import.snippet'] = new \Sulu\Component\Snippet\Import\SnippetImport(($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), ($container->privates['sulu_document_manager.document_registry'] ??= new \Sulu\Component\DocumentManager\DocumentRegistry('en')), ($container->privates['sulu_page.import.manager'] ?? $container->load('getSuluPage_Import_ManagerService')), ($container->services['sulu_page.compat.structure.legacy_property_factory'] ?? self::getSuluPage_Compat_Structure_LegacyPropertyFactoryService($container)), ($container->privates['sulu_snippet.import.webspace.xliff12'] ??= new \Sulu\Component\Import\Format\Xliff12()), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
