<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaListRepresentationFactoryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.media_list_representation_factory' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\ListRepresentationFactory\MediaListRepresentationFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.media_list_representation_factory'] = new \Sulu\Bundle\MediaBundle\Media\ListRepresentationFactory\MediaListRepresentationFactory(($container->services['sulu_media.media_manager'] ?? self::getSuluMedia_MediaManagerService($container)), ($container->services['sulu_media.format_manager'] ?? self::getSuluMedia_FormatManagerService($container)));
    }
}
