<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PageRemoveSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.page_remove_subscriber' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\EventListener\PageRemoveSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['sulu_page.page_remove_subscriber'])) {
            return $container->privates['sulu_page.page_remove_subscriber'];
        }
        $b = ($container->services['sulu.repository.access_control'] ?? self::getSulu_Repository_AccessControlService($container));

        if (isset($container->privates['sulu_page.page_remove_subscriber'])) {
            return $container->privates['sulu_page.page_remove_subscriber'];
        }
        $c = ($container->privates['sulu_security.system_store'] ?? self::getSuluSecurity_SystemStoreService($container));

        if (isset($container->privates['sulu_page.page_remove_subscriber'])) {
            return $container->privates['sulu_page.page_remove_subscriber'];
        }
        $d = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

        if (isset($container->privates['sulu_page.page_remove_subscriber'])) {
            return $container->privates['sulu_page.page_remove_subscriber'];
        }

        return $container->privates['sulu_page.page_remove_subscriber'] = new \Sulu\Bundle\PageBundle\EventListener\PageRemoveSubscriber($a, $b, $c, $d, $container->parameters['sulu_security.permissions']);
    }
}
