<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Document_Subscriber_CopyLocaleService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.document.subscriber.copy_locale' shared service.
     *
     * @return \Sulu\Component\Content\Document\Subscriber\CopyLocaleSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->privates['sulu_document_manager.document.subscriber.copy_locale'])) {
            return $container->privates['sulu_document_manager.document.subscriber.copy_locale'];
        }
        $b = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_document_manager.document.subscriber.copy_locale'])) {
            return $container->privates['sulu_document_manager.document.subscriber.copy_locale'];
        }

        return $container->privates['sulu_document_manager.document.subscriber.copy_locale'] = new \Sulu\Component\Content\Document\Subscriber\CopyLocaleSubscriber($a, $b, ($container->privates['sulu.content.resource_locator.strategy_pool'] ?? $container->load('getSulu_Content_ResourceLocator_StrategyPoolService')));
    }
}
