<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_SessionManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.session_manager' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Session\SessionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container));

        if (isset($container->privates['sulu_document_manager.session_manager'])) {
            return $container->privates['sulu_document_manager.session_manager'];
        }
        $b = ($container->services['sulu_document_manager.live_session'] ?? $container->load('getSuluDocumentManager_LiveSessionService'));

        if (isset($container->privates['sulu_document_manager.session_manager'])) {
            return $container->privates['sulu_document_manager.session_manager'];
        }

        return $container->privates['sulu_document_manager.session_manager'] = new \Sulu\Bundle\DocumentManagerBundle\Session\SessionManager($a, $b);
    }
}
