<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Controller_SnippetService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.controller.snippet' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Controller\SnippetController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.controller.snippet'] = new \Sulu\Bundle\SnippetBundle\Controller\SnippetController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService')), ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), ($container->services['sulu_snippet.repository'] ?? $container->load('getSuluSnippet_RepositoryService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['sulu_snippet.default_snippet.manager'] ?? $container->load('getSuluSnippet_DefaultSnippet_ManagerService')), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')), ($container->services['sulu_hash.request_hash_checker'] ?? $container->load('getSuluHash_RequestHashCheckerService')), ($container->services['sulu_core.list_rest_helper'] ?? $container->load('getSuluCore_ListRestHelperService')), ($container->services['sulu_document_manager.metadata_factory.base'] ?? self::getSuluDocumentManager_MetadataFactory_BaseService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
