<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Repository_ActivityService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.repository.activity' shared service.
     *
     * @return \Sulu\Component\Persistence\Repository\ORM\EntityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->services['sulu.repository.activity'] = $container->createProxy('EntityRepositoryGhost3430f1f', static fn () => \EntityRepositoryGhost3430f1f::createLazyGhost(static fn ($proxy) => self::do($container, $proxy)));
        }

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        return ($lazyLoad->__construct($a, $a->getClassMetadata('Sulu\\Bundle\\ActivityBundle\\Domain\\Model\\Activity')) && false ?: $lazyLoad);
    }
}
