<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_CacheCommandSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_preview.cache_command_subscriber' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\Infrastructure\Symfony\EventSubscriber\CacheCommandSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_preview.cache_command_subscriber'] = new \Sulu\Bundle\PreviewBundle\Infrastructure\Symfony\EventSubscriber\CacheCommandSubscriber(($container->privates['sulu_preview.preview.kernel_factory'] ??= new \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory()), 'dev');
    }
}
