<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Twig_AreaSnippetService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.twig.area_snippet' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Twig\SnippetAreaTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_snippet.resolver'] ?? $container->load('getSuluSnippet_ResolverService'));

        if (isset($container->privates['sulu_snippet.twig.area_snippet'])) {
            return $container->privates['sulu_snippet.twig.area_snippet'];
        }

        return $container->privates['sulu_snippet.twig.area_snippet'] = new \Sulu\Bundle\SnippetBundle\Twig\SnippetAreaTwigExtension(($container->services['sulu_snippet.default_snippet.manager'] ?? $container->load('getSuluSnippet_DefaultSnippet_ManagerService')), ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), $a, ($container->services['sulu_snippet.reference_store.snippet_area'] ??= new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()));
    }
}
