<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Build_Builder_NodeOrderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.build.builder.node_order' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Build\NodeOrderBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.build.builder.node_order'] = new \Sulu\Bundle\PageBundle\Build\NodeOrderBuilder(($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container)), ($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container)), ($container->services['sulu_document_manager.live_session'] ?? $container->load('getSuluDocumentManager_LiveSessionService')), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), ($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)));
    }
}
