<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_WebspaceReferenceStoreService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_website.webspace_reference_store' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\ReferenceStore\WebspaceReferenceStore
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_website.webspace_reference_store'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\WebspaceReferenceStore(($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)));
    }
}
