<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Twig_Navigation_MemoizedService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_website.twig.navigation.memoized' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Twig\Navigation\MemoizedNavigationTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_website.twig.navigation'] ?? $container->load('getSuluWebsite_Twig_NavigationService'));

        if (isset($container->privates['sulu_website.twig.navigation.memoized'])) {
            return $container->privates['sulu_website.twig.navigation.memoized'];
        }

        return $container->privates['sulu_website.twig.navigation.memoized'] = new \Sulu\Bundle\WebsiteBundle\Twig\Navigation\MemoizedNavigationTwigExtension($a, ($container->privates['sulu_core.cache.memoize'] ?? $container->load('getSuluCore_Cache_MemoizeService')), 1);
    }
}
