<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Search_Subscriber_StructureMediaService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.search.subscriber.structure_media' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Search\Subscriber\StructureMediaSearchSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.search.subscriber.structure_media'] = new \Sulu\Bundle\MediaBundle\Search\Subscriber\StructureMediaSearchSubscriber(($container->services['sulu_media.media_manager'] ?? self::getSuluMedia_MediaManagerService($container)), ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), 'sulu-100x100');
    }
}
