<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Type_SingleCollectionSelectionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.type.single_collection_selection' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Content\Types\SingleCollectionSelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.type.single_collection_selection'] = new \Sulu\Bundle\MediaBundle\Content\Types\SingleCollectionSelection(($container->services['sulu_media.collection_manager'] ?? $container->load('getSuluMedia_CollectionManagerService')), ($container->privates['sulu_media.reference_store.collection'] ??= new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()));
    }
}
