<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Core_InstantiatorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.core.instantiator' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Core\InstantiatorSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.metadata_factory'] ?? self::getSuluDocumentManager_MetadataFactoryService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.core.instantiator'])) {
            return $container->privates['sulu_document_manager.subscriber.core.instantiator'];
        }

        return $container->privates['sulu_document_manager.subscriber.core.instantiator'] = new \Sulu\Component\DocumentManager\Subscriber\Core\InstantiatorSubscriber($a);
    }
}
