<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_TargetGroupEvaluationControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_audience_targeting.target_group_evaluation_controller' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Controller\TargetGroupEvaluationController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_audience_targeting.target_group_evaluation_controller'] = new \Sulu\Bundle\AudienceTargetingBundle\Controller\TargetGroupEvaluationController(($container->privates['sulu_audience_targeting.target_group_evaluator'] ?? $container->load('getSuluAudienceTargeting_TargetGroupEvaluatorService')), ($container->services['sulu.repository.target_group'] ?? self::getSulu_Repository_TargetGroupService($container)), ($container->services['sulu_audience_targeting.target_group_store'] ??= new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore()), 'X-Sulu-Target-Group');
    }
}
