<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluReference_RefreshCommandService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_reference.refresh_command' shared service.
     *
     * @return \Sulu\Bundle\ReferenceBundle\UserInterface\Command\RefreshCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_reference.refresh_command'] = $instance = new \Sulu\Bundle\ReferenceBundle\UserInterface\Command\RefreshCommand(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_page.page_reference_refresher'] ?? $container->load('getSuluPage_PageReferenceRefresherService'));
            yield 1 => ($container->privates['sulu_snippet.snippet_reference_refresher'] ?? $container->load('getSuluSnippet_SnippetReferenceRefresherService'));
        }, 2), ($container->privates['sulu_reference.reference_repository'] ?? $container->load('getSuluReference_ReferenceRepositoryService')), 'admin');

        $instance->setName('sulu:reference:refresh');

        return $instance;
    }
}
