<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Import_ManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.import.manager' shared service.
     *
     * @return \Sulu\Component\Import\Manager\ImportManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.import.manager'] = new \Sulu\Component\Import\Manager\ImportManager(($container->services['sulu.content.type_manager'] ?? self::getSulu_Content_TypeManagerService($container)));
    }
}
