<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_SmartContent_DataProvider_MediaService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.smart_content.data_provider.media' shared service.
     *
     * @return \Sulu\Component\Media\SmartContent\MediaDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_media.smart_content.data_provider.media'] = new \Sulu\Component\Media\SmartContent\MediaDataProvider(($container->privates['sulu_media.smart_content.data_provider.media.repository'] ?? $container->load('getSuluMedia_SmartContent_DataProvider_Media_RepositoryService')), ($container->services['sulu_media.collection_manager'] ?? $container->load('getSuluMedia_CollectionManagerService')), ($container->services['sulu_core.array_serializer'] ?? $container->load('getSuluCore_ArraySerializerService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['sulu_media.reference_store.media'] ??= new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)), ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), $container->parameters['sulu_security.permissions'], $container->hasParameter("sulu_audience_targeting.enabled"), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
