<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_ResolverService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.resolver' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Snippet\SnippetResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService'));

        if (isset($container->services['sulu_snippet.resolver'])) {
            return $container->services['sulu_snippet.resolver'];
        }
        $b = ($container->services['sulu_website.resolver.structure'] ?? $container->load('getSuluWebsite_Resolver_StructureService'));

        if (isset($container->services['sulu_snippet.resolver'])) {
            return $container->services['sulu_snippet.resolver'];
        }

        return $container->services['sulu_snippet.resolver'] = new \Sulu\Bundle\SnippetBundle\Snippet\SnippetResolver($a, $b);
    }
}
