<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_RulesCollectionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_audience_targeting.rules_collection' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Rule\RuleCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_audience_targeting.rules_collection'] = new \Sulu\Bundle\AudienceTargetingBundle\Rule\RuleCollection(['page' => ($container->privates['sulu_audience_targeting.rules.page'] ?? $container->load('getSuluAudienceTargeting_Rules_PageService')), 'locale' => ($container->privates['sulu_audience_targeting.rules.locale'] ?? $container->load('getSuluAudienceTargeting_Rules_LocaleService')), 'referrer' => ($container->privates['sulu_audience_targeting.rules.referrer'] ?? $container->load('getSuluAudienceTargeting_Rules_ReferrerService')), 'query_string' => ($container->privates['sulu_audience_targeting.rules.query_string'] ?? $container->load('getSuluAudienceTargeting_Rules_QueryStringService')), 'browser' => ($container->privates['sulu_audience_targeting.rules.browser'] ?? $container->load('getSuluAudienceTargeting_Rules_BrowserService')), 'os' => ($container->privates['sulu_audience_targeting.rules.os'] ?? $container->load('getSuluAudienceTargeting_Rules_OsService')), 'device' => ($container->privates['sulu_audience_targeting.rules.device'] ?? $container->load('getSuluAudienceTargeting_Rules_DeviceService'))]);
    }
}
