<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Extension_ManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.extension.manager' shared service.
     *
     * @return \Sulu\Component\Content\Extension\ExtensionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['sulu_page.extension.manager'] = $instance = new \Sulu\Component\Content\Extension\ExtensionManager();

        $instance->addExtension(($container->privates['sulu_page.extension.seo'] ??= new \Sulu\Bundle\PageBundle\Content\Structure\SeoStructureExtension()));
        $instance->addExtension(($container->privates['sulu_page.extension.excerpt'] ?? $container->load('getSuluPage_Extension_ExcerptService')));
        $instance->addExtension(($container->privates['perspeqtive_sulu_snippet_tabs.extension.services'] ?? $container->load('getPerspeqtiveSuluSnippetTabs_Extension_ServicesService')));
        $instance->addExtension(($container->privates['perspeqtive_sulu_snippet_tabs.extension.events'] ?? $container->load('getPerspeqtiveSuluSnippetTabs_Extension_EventsService')));

        return $instance;
    }
}
