<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Type_MediaSelectionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.type.media_selection' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Content\Types\MediaSelectionContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.type.media_selection'] = new \Sulu\Bundle\MediaBundle\Content\Types\MediaSelectionContentType(($container->services['sulu_media.media_manager'] ?? self::getSuluMedia_MediaManagerService($container)), ($container->privates['sulu_media.reference_store.media'] ??= new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()), ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), $container->parameters['sulu_security.permissions'], ($container->privates['sulu_admin.property_metadata_min_max_value_resolver'] ??= new \Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata\PropertyMetadataMinMaxValueResolver()));
    }
}
