<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_SecurityContextVoterService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.security_context_voter' shared service.
     *
     * @return \Sulu\Component\Security\Authorization\SecurityContextVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_security.access_control_manager'] ?? self::getSuluSecurity_AccessControlManagerService($container));

        if (isset($container->privates['sulu_security.security_context_voter'])) {
            return $container->privates['sulu_security.security_context_voter'];
        }

        return $container->privates['sulu_security.security_context_voter'] = new \Sulu\Component\Security\Authorization\SecurityContextVoter($a, $container->parameters['permissions']);
    }
}
