<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Suscriber_Behavior_LastModifiedService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.suscriber.behavior.last_modified' shared service.
     *
     * @return \Sulu\Component\Content\Document\Subscriber\LastModifiedSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.metadata_factory'] ?? self::getSuluDocumentManager_MetadataFactoryService($container));

        if (isset($container->privates['sulu_document_manager.suscriber.behavior.last_modified'])) {
            return $container->privates['sulu_document_manager.suscriber.behavior.last_modified'];
        }

        return $container->privates['sulu_document_manager.suscriber.behavior.last_modified'] = new \Sulu\Component\Content\Document\Subscriber\LastModifiedSubscriber(($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)), ($container->services['sulu.repository.user'] ?? self::getSulu_Repository_UserService($container)), $a);
    }
}
