<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_FormatCacheClearerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.format_cache_clearer' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Media\FormatCache\FormatCacheClearer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_media.format_cache_clearer'] = $instance = new \Sulu\Bundle\MediaBundle\Media\FormatCache\FormatCacheClearer();

        $instance->add(($container->services['sulu_media.format_cache'] ?? self::getSuluMedia_FormatCacheService($container)), 'local');

        return $instance;
    }
}
