<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_Content_Type_TargetGroupSelectionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_audience_targeting.content.type.target_group_selection' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Content\Types\TargetGroupSelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_audience_targeting.content.type.target_group_selection'] = new \Sulu\Bundle\AudienceTargetingBundle\Content\Types\TargetGroupSelection(($container->services['sulu.repository.target_group'] ?? self::getSulu_Repository_TargetGroupService($container)));
    }
}
