<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Phpcr_MixinService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.phpcr.mixin' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\MixinSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.metadata_factory'] ?? self::getSuluDocumentManager_MetadataFactoryService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.phpcr.mixin'])) {
            return $container->privates['sulu_document_manager.subscriber.phpcr.mixin'];
        }

        return $container->privates['sulu_document_manager.subscriber.phpcr.mixin'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\MixinSubscriber($a, ($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)));
    }
}
