<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_Serializer_EventSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_custom_urls.serializer.event_subscriber' shared service.
     *
     * @return \Sulu\Bundle\CustomUrlBundle\EventListener\CustomUrlSerializeEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_custom_urls.serializer.event_subscriber'])) {
            return $container->privates['sulu_custom_urls.serializer.event_subscriber'];
        }

        return $container->privates['sulu_custom_urls.serializer.event_subscriber'] = new \Sulu\Bundle\CustomUrlBundle\EventListener\CustomUrlSerializeEventSubscriber(($container->privates['sulu_custom_urls.domain_generator'] ?? $container->load('getSuluCustomUrls_DomainGeneratorService')), ($container->services['sulu_security.user_manager'] ?? $container->load('getSuluSecurity_UserManagerService')), $a);
    }
}
