<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Twig_ContentService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_website.twig.content' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Twig\Content\ContentTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService'));

        if (isset($container->privates['sulu_website.twig.content'])) {
            return $container->privates['sulu_website.twig.content'];
        }
        $b = ($container->services['sulu_website.resolver.structure'] ?? $container->load('getSuluWebsite_Resolver_StructureService'));

        if (isset($container->privates['sulu_website.twig.content'])) {
            return $container->privates['sulu_website.twig.content'];
        }
        $c = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['sulu_website.twig.content'])) {
            return $container->privates['sulu_website.twig.content'];
        }
        $d = ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container));

        if (isset($container->privates['sulu_website.twig.content'])) {
            return $container->privates['sulu_website.twig.content'];
        }

        return $container->privates['sulu_website.twig.content'] = new \Sulu\Bundle\WebsiteBundle\Twig\Content\ContentTwigExtension($a, $b, $c, ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)), $d, ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $container->parameters['sulu_website.enabled_twig_attributes']);
    }
}
