<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_DocumentDomainEventCollectorSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.document_domain_event_collector_subscriber' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Collector\DocumentDomainEventCollectorSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.document_domain_event_collector'] ?? $container->load('getSuluDocumentManager_DocumentDomainEventCollectorService'));

        if (isset($container->privates['sulu_document_manager.document_domain_event_collector_subscriber'])) {
            return $container->privates['sulu_document_manager.document_domain_event_collector_subscriber'];
        }

        return $container->privates['sulu_document_manager.document_domain_event_collector_subscriber'] = new \Sulu\Bundle\DocumentManagerBundle\Collector\DocumentDomainEventCollectorSubscriber($a);
    }
}
