<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluTag_Content_Type_TagSelectionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_tag.content.type.tag_selection' shared service.
     *
     * @return \Sulu\Bundle\TagBundle\Content\Types\TagSelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_tag.content.type.tag_selection'] = new \Sulu\Bundle\TagBundle\Content\Types\TagSelection(($container->services['sulu_tag.tag_manager'] ?? self::getSuluTag_TagManagerService($container)));
    }
}
