<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Command_LocaleCopyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.command.locale_copy' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Command\SnippetLocaleCopyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_snippet.command.locale_copy'] = $instance = new \Sulu\Bundle\SnippetBundle\Command\SnippetLocaleCopyCommand(($container->services['sulu_snippet.repository'] ?? $container->load('getSuluSnippet_RepositoryService')), ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService')), ($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container)), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), 'i18n');

        $instance->setName('sulu:snippet:locale-copy');
        $instance->setDescription('Copy snippet nodes from one locale to another');

        return $instance;
    }
}
