<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_NameResolverService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.name_resolver' shared service.
     *
     * @return \Sulu\Component\DocumentManager\NameResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_document_manager.name_resolver'] = new \Sulu\Component\DocumentManager\NameResolver();
    }
}
