<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_SaveWithFormDialogToolbarActionSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_admin.save_with_form_dialog_toolbar_action_subscriber' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Serializer\Subscriber\SaveWithFormDialogToolbarActionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.save_with_form_dialog_toolbar_action_subscriber'] = new \Sulu\Bundle\AdminBundle\Serializer\Subscriber\SaveWithFormDialogToolbarActionSubscriber(($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
