<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_PhpcrAccessControlProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.phpcr_access_control_provider' shared service.
     *
     * @return \Sulu\Component\Security\Authorization\AccessControl\PhpcrAccessControlProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.phpcr_access_control_provider'] = new \Sulu\Component\Security\Authorization\AccessControl\PhpcrAccessControlProvider(($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['sulu.repository.role'] ?? self::getSulu_Repository_RoleService($container)), $container->parameters['permissions']);
    }
}
