<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_Block_HiddenVisitorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu.content.type.block.hidden_visitor' shared service.
     *
     * @return \Sulu\Component\Content\Types\Block\HiddenBlockVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu.content.type.block.hidden_visitor'] = new \Sulu\Component\Content\Types\Block\HiddenBlockVisitor();
    }
}
