<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Document_Subscriber_FallbackLocalizationService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.document.subscriber.fallback_localization' shared service.
     *
     * @return \Sulu\Component\Content\Document\Subscriber\FallbackLocalizationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_document_manager.document.subscriber.fallback_localization'])) {
            return $container->privates['sulu_document_manager.document.subscriber.fallback_localization'];
        }

        return $container->privates['sulu_document_manager.document.subscriber.fallback_localization'] = new \Sulu\Component\Content\Document\Subscriber\FallbackLocalizationSubscriber(($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)), $a, ($container->privates['sulu_document_manager.document_registry'] ??= new \Sulu\Component\DocumentManager\DocumentRegistry('en')), ($container->services['sulu.content.localization_finder'] ?? self::getSulu_Content_LocalizationFinderService($container)));
    }
}
