<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Document_Subscriber_RouteService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.document.subscriber.route' shared service.
     *
     * @return \Sulu\Component\Content\Document\Subscriber\RouteSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->privates['sulu_document_manager.document.subscriber.route'])) {
            return $container->privates['sulu_document_manager.document.subscriber.route'];
        }
        $b = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu_document_manager.document.subscriber.route'])) {
            return $container->privates['sulu_document_manager.document.subscriber.route'];
        }
        $c = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['sulu_document_manager.document.subscriber.route'])) {
            return $container->privates['sulu_document_manager.document.subscriber.route'];
        }

        return $container->privates['sulu_document_manager.document.subscriber.route'] = new \Sulu\Component\Content\Document\Subscriber\RouteSubscriber($a, $b, $c, ($container->privates['sulu_document_manager.node_manager'] ?? self::getSuluDocumentManager_NodeManagerService($container)));
    }
}
