<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_SmartContent_DataProvider_Content_QueryBuilderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.smart_content.data_provider.content.query_builder' shared service.
     *
     * @return \Sulu\Component\Content\SmartContent\QueryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService'));

        if (isset($container->privates['sulu_page.smart_content.data_provider.content.query_builder'])) {
            return $container->privates['sulu_page.smart_content.data_provider.content.query_builder'];
        }
        $b = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['sulu_page.smart_content.data_provider.content.query_builder'])) {
            return $container->privates['sulu_page.smart_content.data_provider.content.query_builder'];
        }

        return $container->privates['sulu_page.smart_content.data_provider.content.query_builder'] = new \Sulu\Component\Content\SmartContent\QueryBuilder(($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), $a, $b, 'i18n');
    }
}
