<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_FormMetadataProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_admin.form_metadata_provider' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\FormMetadataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.form_metadata_provider'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\FormMetadataProvider(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu_admin.xml_form_metadata_loader'] ?? $container->load('getSuluAdmin_XmlFormMetadataLoaderService'));
            yield 1 => ($container->privates['sulu_admin.structure_form_metadata_loader'] ?? $container->load('getSuluAdmin_StructureFormMetadataLoaderService'));
        }, 2), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu.content.type.block.global_block_visitor'] ?? $container->load('getSulu_Content_Type_Block_GlobalBlockVisitorService'));
            yield 1 => ($container->privates['sulu_admin.form_metadata_validator.locale_options'] ??= new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\Visitor\LocalesOptionFormMetadataVisitor());
            yield 2 => ($container->privates['sulu_security.password_pattern_form_metadata_visitor'] ?? $container->load('getSuluSecurity_PasswordPatternFormMetadataVisitorService'));
            yield 3 => ($container->privates['sulu_security.two_factor_form_metadata_visitor'] ?? $container->load('getSuluSecurity_TwoFactorFormMetadataVisitorService'));
            yield 4 => ($container->privates['sulu_admin.expression_form_metadata_visitor'] ?? $container->load('getSuluAdmin_ExpressionFormMetadataVisitorService'));
        }, 5), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu.content.type.block.global_block_visitor'] ?? $container->load('getSulu_Content_Type_Block_GlobalBlockVisitorService'));
            yield 1 => ($container->privates['sulu_admin.expression_form_metadata_visitor'] ?? $container->load('getSuluAdmin_ExpressionFormMetadataVisitorService'));
            yield 2 => ($container->privates['sulu_admin.tag_filter_typed_form_metadata_visitor'] ??= new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\TagFilterTypedFormMetadataVisitor());
        }, 3), 'en');
    }
}
