<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Phpcr_RefreshService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.phpcr.refresh' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Phpcr\RefreshSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.event_dispatcher.standard'] ?? self::getSuluDocumentManager_EventDispatcher_StandardService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.phpcr.refresh'])) {
            return $container->privates['sulu_document_manager.subscriber.phpcr.refresh'];
        }

        return $container->privates['sulu_document_manager.subscriber.phpcr.refresh'] = new \Sulu\Component\DocumentManager\Subscriber\Phpcr\RefreshSubscriber($a, ($container->privates['sulu_document_manager.document_registry'] ??= new \Sulu\Component\DocumentManager\DocumentRegistry('en')));
    }
}
