<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_Serializer_Handler_SecuredEntityService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.serializer.handler.secured_entity' shared service.
     *
     * @return \Sulu\Component\Security\Serializer\Subscriber\SecuredEntitySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_security.access_control_manager'] ?? self::getSuluSecurity_AccessControlManagerService($container));

        if (isset($container->privates['sulu_security.serializer.handler.secured_entity'])) {
            return $container->privates['sulu_security.serializer.handler.secured_entity'];
        }

        return $container->privates['sulu_security.serializer.handler.secured_entity'] = new \Sulu\Component\Security\Serializer\Subscriber\SecuredEntitySubscriber($a, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
