<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Cache_MemoizeService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.cache.memoize' shared service.
     *
     * @return \Sulu\Component\Cache\Memoize
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_core.cache.memoize'] = new \Sulu\Component\Cache\Memoize(($container->privates['sulu_core.cache.memoize.cache'] ?? $container->load('getSuluCore_Cache_Memoize_CacheService')), 1);
    }
}
