<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_RepositoryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.repository' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Snippet\SnippetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.repository'] = new \Sulu\Bundle\SnippetBundle\Snippet\SnippetRepository(($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container)), ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService')), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)));
    }
}
