<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_LoginFailureListenerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.login_failure_listener' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\EventListener\AuhenticationFailureListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.login_failure_listener'] = new \Sulu\Bundle\SecurityBundle\EventListener\AuhenticationFailureListener(($container->services['sulu_security.encoder_factory'] ?? $container->load('getSuluSecurity_EncoderFactoryService')), ($container->services['sulu.repository.user'] ?? self::getSulu_Repository_UserService($container)));
    }
}
