<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_ContextsControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_security.contexts_controller' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Controller\ContextsController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.contexts_controller'] = new \Sulu\Bundle\SecurityBundle\Controller\ContextsController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_admin.admin_pool'] ?? $container->load('getSuluAdmin_AdminPoolService')));
    }
}
