<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_QueryExecutorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu.content.query_executor' shared service.
     *
     * @return \Sulu\Component\Content\Query\ContentQueryExecutor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['sulu.content.query_executor'])) {
            return $container->privates['sulu.content.query_executor'];
        }
        $b = ($container->services['sulu.content.mapper'] ?? $container->load('getSulu_Content_MapperService'));

        if (isset($container->privates['sulu.content.query_executor'])) {
            return $container->privates['sulu.content.query_executor'];
        }

        return $container->privates['sulu.content.query_executor'] = new \Sulu\Component\Content\Query\ContentQueryExecutor($a, $b, NULL);
    }
}
