<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_TwigExtension_User_CacheService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.twig_extension.user.cache' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Entity\PositionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_security.twig_extension.user.cache'] = \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap(($container->privates['sulu_security.twig_extension.user.cache_adapter'] ??= new \Symfony\Component\Cache\Adapter\ArrayAdapter()));
    }
}
