<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_SitemapService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_website.sitemap' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Sitemap\SitemapGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu.content.query_executor'] ?? $container->load('getSulu_Content_QueryExecutorService'));

        if (isset($container->privates['sulu_website.sitemap'])) {
            return $container->privates['sulu_website.sitemap'];
        }
        $b = ($container->privates['sulu_website.sitemap.query_builder'] ?? $container->load('getSuluWebsite_Sitemap_QueryBuilderService'));

        if (isset($container->privates['sulu_website.sitemap'])) {
            return $container->privates['sulu_website.sitemap'];
        }

        return $container->privates['sulu_website.sitemap'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\SitemapGenerator($a, ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), $b, 'dev');
    }
}
