<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Command_WebspaceCopyService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.command.webspace_copy' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Command\WebspaceCopyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_page.command.webspace_copy'] = $instance = new \Sulu\Bundle\PageBundle\Command\WebspaceCopyCommand(($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container)), ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container)), ($container->services['sulu_markup.parser.html_extractor'] ??= new \Sulu\Bundle\MarkupBundle\Markup\HtmlTagExtractor('sulu')));

        $instance->setName('sulu:webspaces:copy');
        $instance->setDescription('Copies a given webspace with given locale to a destination webspace with a destination locale.');

        return $instance;
    }
}
