<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_UrlProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_custom_urls.url_provider' shared service.
     *
     * @return \Sulu\Component\CustomUrl\WebspaceCustomUrlProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_custom_urls.manager'] ?? $container->load('getSuluCustomUrls_ManagerService'));

        if (isset($container->privates['sulu_custom_urls.url_provider'])) {
            return $container->privates['sulu_custom_urls.url_provider'];
        }

        return $container->privates['sulu_custom_urls.url_provider'] = new \Sulu\Component\CustomUrl\WebspaceCustomUrlProvider($a);
    }
}
