<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Subscriber_Behavior_AliasService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.subscriber.behavior.alias' shared service.
     *
     * @return \Sulu\Component\DocumentManager\Subscriber\Behavior\Path\AliasFilingSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.behavior.alias'])) {
            return $container->privates['sulu_document_manager.subscriber.behavior.alias'];
        }
        $b = ($container->services['sulu_document_manager.live_session'] ?? $container->load('getSuluDocumentManager_LiveSessionService'));

        if (isset($container->privates['sulu_document_manager.subscriber.behavior.alias'])) {
            return $container->privates['sulu_document_manager.subscriber.behavior.alias'];
        }
        $c = ($container->services['sulu_document_manager.metadata_factory.base'] ?? self::getSuluDocumentManager_MetadataFactory_BaseService($container));

        if (isset($container->privates['sulu_document_manager.subscriber.behavior.alias'])) {
            return $container->privates['sulu_document_manager.subscriber.behavior.alias'];
        }

        return $container->privates['sulu_document_manager.subscriber.behavior.alias'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Path\AliasFilingSubscriber($a, $b, $c);
    }
}
