<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_PageTreeRoute_MoverService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_route.page_tree_route.mover' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\PageTree\PageTreeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_route.page_tree_route.mover'] = new \Sulu\Bundle\RouteBundle\PageTree\PageTreeRepository(($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['sulu_page.structure.factory'] ?? self::getSuluPage_Structure_FactoryService($container)), ($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)), ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container)));
    }
}
