<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_ResourceLocator_Strategy_TreeFullEditService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu.content.resource_locator.strategy.tree_full_edit' shared service.
     *
     * @return \Sulu\Component\Content\Types\ResourceLocator\Strategy\TreeFullEditStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container));

        if (isset($container->privates['sulu.content.resource_locator.strategy.tree_full_edit'])) {
            return $container->privates['sulu.content.resource_locator.strategy.tree_full_edit'];
        }
        $b = ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container));

        if (isset($container->privates['sulu.content.resource_locator.strategy.tree_full_edit'])) {
            return $container->privates['sulu.content.resource_locator.strategy.tree_full_edit'];
        }

        return $container->privates['sulu.content.resource_locator.strategy.tree_full_edit'] = new \Sulu\Component\Content\Types\ResourceLocator\Strategy\TreeFullEditStrategy(($container->privates['sulu.content.resource_locator.mapper.phpcr'] ?? $container->load('getSulu_Content_ResourceLocator_Mapper_PhpcrService')), ($container->services['sulu.content.path_cleaner'] ?? self::getSulu_Content_PathCleanerService($container)), ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), ($container->services['sulu.content.type_manager'] ?? self::getSulu_Content_TypeManagerService($container)), ($container->services['sulu.util.node_helper'] ?? self::getSulu_Util_NodeHelperService($container)), $a, $b, ($container->privates['sulu.content.resource_locator.strategy.tree_generator'] ??= new \Sulu\Component\Content\Types\ResourceLocator\Strategy\TreeGenerator()));
    }
}
