<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMarkup_MailerListenerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_markup.mailer_listener' shared service.
     *
     * @return \Sulu\Bundle\MarkupBundle\Listener\MailerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_markup.parser'] ?? self::getSuluMarkup_ParserService($container));

        if (isset($container->privates['sulu_markup.mailer_listener'])) {
            return $container->privates['sulu_markup.mailer_listener'];
        }

        return $container->privates['sulu_markup.mailer_listener'] = new \Sulu\Bundle\MarkupBundle\Listener\MailerListener($a, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), 'en');
    }
}
