<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_IconProvider_SvgService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_admin.icon_provider.svg' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Icon\providers\SvgProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_admin.icon_provider.svg'] = new \Sulu\Bundle\AdminBundle\Icon\providers\SvgProvider(($container->privates['sulu_admin.icon_cache'] ?? $container->load('getSuluAdmin_IconCacheService')));
    }
}
