<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_TestService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.test' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.firewall.map.config.test'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('test', 'security.user_checker', NULL, true, false, 'test_user_provider', 'test', 'security.authenticator.http_basic.test', NULL, NULL, ['http_basic'], NULL, NULL);
    }
}
