<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPreview_PreviewObjectProviderRegistryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_preview.preview_object_provider_registry' shared service.
     *
     * @return \Sulu\Bundle\PreviewBundle\Preview\Object\PreviewObjectProviderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_preview.preview_object_provider_registry'] = new \Sulu\Bundle\PreviewBundle\Preview\Object\PreviewObjectProviderRegistry(['pages' => ($container->privates['sulu_page.preview.object_provider'] ?? $container->load('getSuluPage_Preview_ObjectProviderService'))]);
    }
}
