<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Preview_ObjectProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.preview.object_provider' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Preview\PageObjectProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.preview.object_provider'] = new \Sulu\Bundle\PageBundle\Preview\PageObjectProvider(($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService')), ($container->services['sulu_document_manager.document_inspector'] ?? self::getSuluDocumentManager_DocumentInspectorService($container)));
    }
}
