<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluTag_Search_TagsConverterService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_tag.search.tags_converter' shared service.
     *
     * @return \Sulu\Bundle\TagBundle\Search\TagsConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_tag.tag_manager'] ?? self::getSuluTag_TagManagerService($container));

        if (isset($container->privates['sulu_tag.search.tags_converter'])) {
            return $container->privates['sulu_tag.search.tags_converter'];
        }

        return $container->privates['sulu_tag.search.tags_converter'] = new \Sulu\Bundle\TagBundle\Search\TagsConverter($a);
    }
}
