<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_AdminPoolService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_admin.admin_pool' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Admin\AdminPool
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['sulu_admin.admin_pool'] = $instance = new \Sulu\Bundle\AdminBundle\Admin\AdminPool();

        $a = ($container->privates['sulu_admin.view_builder_factory'] ??= new \Sulu\Bundle\AdminBundle\Admin\View\ViewBuilderFactory());
        $b = ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container));
        $c = ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container));
        $d = ($container->privates['sulu_activity.activity_list_view_builder_factory'] ?? $container->load('getSuluActivity_ActivityListViewBuilderFactoryService'));
        $e = ($container->services['router'] ?? self::getRouterService($container));
        $f = ($container->services['sulu.core.localization_manager'] ?? $container->load('getSulu_Core_LocalizationManagerService'));
        $g = ($container->privates['sulu_reference.reference_list_view_builder_factory'] ?? $container->load('getSuluReference_ReferenceListViewBuilderFactoryService'));

        $instance->addAdmin(new \Sulu\Bundle\SearchBundle\Admin\SearchAdmin($a));
        $instance->addAdmin(new \Sulu\Bundle\PageBundle\Admin\PageAdmin($a, $b, $c, ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container)), ($container->privates['sulu_page.teaser.provider_pool'] ?? $container->load('getSuluPage_Teaser_ProviderPoolService')), false, $d));
        $instance->addAdmin(new \Sulu\Bundle\ContactBundle\Admin\ContactAdmin($a, $c, ($container->services['doctrine'] ?? self::getDoctrineService($container))));
        $instance->addAdmin(new \Sulu\Bundle\WebsiteBundle\Admin\WebsiteAdmin($a, $b, $c, $e));
        $instance->addAdmin(new \Sulu\Bundle\TagBundle\Admin\TagAdmin($a, $c));
        $instance->addAdmin(new \Sulu\Bundle\MediaBundle\Admin\MediaAdmin($a, $c, $f, $e, $b, $d, $g));
        $instance->addAdmin(new \Sulu\Bundle\CategoryBundle\Admin\CategoryAdmin($a, $c, $f));
        $instance->addAdmin(new \Sulu\Bundle\SnippetBundle\Admin\SnippetAdmin($a, $c, $b, true, $d, $g));
        $instance->addAdmin(new \Sulu\Bundle\ActivityBundle\Infrastructure\Sulu\Admin\ActivityAdmin($a, $c));
        $instance->addAdmin(new \Sulu\Bundle\CustomUrlBundle\Admin\CustomUrlAdmin($b, $a, $c));
        $instance->addAdmin(new \Sulu\Bundle\PreviewBundle\Admin\PreviewAdmin($e, 500, 'auto', $container->parameters['kernel.bundles']));
        $instance->addAdmin(new \Sulu\Bundle\AudienceTargetingBundle\Admin\AudienceTargetingAdmin($a, ($container->privates['sulu_audience_targeting.rules_collection'] ?? $container->load('getSuluAudienceTargeting_RulesCollectionService')), $c));
        $instance->addAdmin(new \Sulu\Bundle\TrashBundle\Infrastructure\Sulu\Admin\TrashAdmin($a, $c, $f, new RewindableGenerator(function () use ($container) {
            yield 'pages' => ($container->privates['sulu_page.page_trash_item_handler'] ?? $container->load('getSuluPage_PageTrashItemHandlerService'));
            yield 'accounts' => ($container->privates['sulu_contact.account_trash_item_handler'] ?? $container->load('getSuluContact_AccountTrashItemHandlerService'));
            yield 'contacts' => ($container->privates['sulu_contact.contact_trash_item_handler'] ?? $container->load('getSuluContact_ContactTrashItemHandlerService'));
            yield 'analytics' => ($container->privates['sulu_website.analytics_trash_item_handler'] ?? $container->load('getSuluWebsite_AnalyticsTrashItemHandlerService'));
            yield 'tags' => ($container->privates['sulu_tag.tag_trash_item_handler'] ?? $container->load('getSuluTag_TagTrashItemHandlerService'));
            yield 'media' => ($container->privates['sulu_media.media_trash_item_handler'] ?? $container->load('getSuluMedia_MediaTrashItemHandlerService'));
            yield 'collections' => ($container->privates['sulu_media.collection_trash_item_handler'] ?? $container->load('getSuluMedia_CollectionTrashItemHandlerService'));
            yield 'categories' => ($container->privates['sulu_category.category_trash_item_handler'] ?? $container->load('getSuluCategory_CategoryTrashItemHandlerService'));
            yield 'snippets' => ($container->privates['sulu_snippet.snippet_trash_item_handler'] ?? $container->load('getSuluSnippet_SnippetTrashItemHandlerService'));
            yield 'custom_urls' => ($container->privates['sulu_custom_urls.custom_url_trash_item_handler'] ?? $container->load('getSuluCustomUrls_CustomUrlTrashItemHandlerService'));
        }, 10)));
        $instance->addAdmin(new \Sulu\Bundle\ReferenceBundle\Infrastructure\Sulu\Admin\ReferenceAdmin());
        $instance->addAdmin(new \PERSPEQTIVE\SuluSnippetTabsBundle\Admin\ConfiguredSnippetTabAdmin($a, $c, ($container->privates['perspeqtive_sulu_snippet_tabs.tabs.tab_config_collection_provider'] ?? $container->load('getPerspeqtiveSuluSnippetTabs_Tabs_TabConfigCollectionProviderService'))));
        $instance->addAdmin(new \Sulu\Bundle\SecurityBundle\Admin\SecurityAdmin($a, $c, $e, ($container->services['translator'] ?? self::getTranslatorService($container)), $instance, $container->parameters['sulu_admin.resources']));

        return $instance;
    }
}
