<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_Block_ScheduleVisitorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu.content.type.block.schedule_visitor' shared service.
     *
     * @return \Sulu\Component\Content\Types\Block\ScheduleBlockVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu.content.type.block.schedule_visitor'] = new \Sulu\Component\Content\Types\Block\ScheduleBlockVisitor(($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), ($container->privates['sulu_http_cache.cache_lifetime.request_store'] ?? $container->load('getSuluHttpCache_CacheLifetime_RequestStoreService')));
    }
}
