<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_BlockService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.content.type.block' shared service.
     *
     * @return \Sulu\Component\Content\Types\BlockContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.type.block'] = new \Sulu\Component\Content\Types\BlockContentType(($container->services['sulu.content.type_manager'] ?? self::getSulu_Content_TypeManagerService($container)), 'i18n', ($container->services['sulu_core.webspace.request_analyzer'] ?? self::getSuluCore_Webspace_RequestAnalyzerService($container)), ($container->services['sulu_audience_targeting.target_group_store'] ??= new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore()), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['sulu.content.type.block.hidden_visitor'] ??= new \Sulu\Component\Content\Types\Block\HiddenBlockVisitor());
            yield 1 => ($container->privates['sulu.content.type.block.segment_visitor'] ?? $container->load('getSulu_Content_Type_Block_SegmentVisitorService'));
            yield 2 => ($container->privates['sulu.content.type.block.schedule_visitor'] ?? $container->load('getSulu_Content_Type_Block_ScheduleVisitorService'));
            yield 3 => ($container->privates['sulu_audience_targeting.target_group_block_visitor'] ?? $container->load('getSuluAudienceTargeting_TargetGroupBlockVisitorService'));
        }, 4));
    }
}
