<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluContact_AccountManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_contact.account_manager' shared service.
     *
     * @return \Sulu\Bundle\ContactBundle\Contact\AccountManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_contact.account_manager'] = new \Sulu\Bundle\ContactBundle\Contact\AccountManager(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sulu_tag.tag_manager'] ?? self::getSuluTag_TagManagerService($container)), ($container->services['sulu_media.media_manager'] ?? self::getSuluMedia_MediaManagerService($container)), ($container->services['sulu_contact.account_factory'] ??= new \Sulu\Bundle\ContactBundle\Contact\AccountFactory('Sulu\\Bundle\\ContactBundle\\Entity\\Account')), ($container->services['sulu.repository.account'] ?? $container->load('getSulu_Repository_AccountService')), ($container->services['sulu.repository.contact'] ?? $container->load('getSulu_Repository_ContactService')), ($container->services['sulu.repository.media'] ?? self::getSulu_Repository_MediaService($container)), ($container->privates['sulu_activity.domain_event_collector'] ?? self::getSuluActivity_DomainEventCollectorService($container)), 'Sulu\\Bundle\\ContactBundle\\Entity\\Account');
    }
}
