<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_LanguageControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.language_controller' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Controller\LanguageController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.language_controller'] = new \Sulu\Bundle\SnippetBundle\Controller\LanguageController(($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)));
    }
}
