<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_Type_TextAreaService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.content.type.text_area' shared service.
     *
     * @return \Sulu\Component\Content\Types\TextLine
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.type.text_area'] = new \Sulu\Component\Content\Types\TextLine();
    }
}
