<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_CacheInvalidationSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.cache_invalidation_subscriber' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\EventListener\CacheInvalidationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_snippet.cache_invalidation_subscriber'] = new \Sulu\Bundle\SnippetBundle\EventListener\CacheInvalidationSubscriber(($container->services['sulu_snippet.default_snippet.manager'] ?? $container->load('getSuluSnippet_DefaultSnippet_ManagerService')), NULL, []);
    }
}
