<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_SnippetReferenceRefresherService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.snippet_reference_refresher' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Reference\Refresh\SnippetReferenceRefresher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_snippet.snippet_reference_refresher'] = new \Sulu\Bundle\SnippetBundle\Reference\Refresh\SnippetReferenceRefresher(($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container)), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->privates['sulu_snippet.snippet_reference_provider'] ?? $container->load('getSuluSnippet_SnippetReferenceProviderService')), 'admin');
    }
}
