<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_HttpCache_ClearerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_website.http_cache.clearer' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Cache\CacheClearer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_website.http_cache.clearer'] = new \Sulu\Bundle\WebsiteBundle\Cache\CacheClearer(($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), 'dev', ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), \dirname(__DIR__, 4), NULL, true);
    }
}
