<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Teaser_ContentTypeService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_page.teaser.content_type' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Teaser\TeaserContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_page.teaser.provider_pool'] ?? $container->load('getSuluPage_Teaser_ProviderPoolService'));

        if (isset($container->services['sulu_page.teaser.content_type'])) {
            return $container->services['sulu_page.teaser.content_type'];
        }
        $b = ($container->privates['sulu_page.teaser.manager'] ?? $container->load('getSuluPage_Teaser_ManagerService'));

        if (isset($container->services['sulu_page.teaser.content_type'])) {
            return $container->services['sulu_page.teaser.content_type'];
        }

        return $container->services['sulu_page.teaser.content_type'] = new \Sulu\Bundle\PageBundle\Teaser\TeaserContentType($a, $b, ($container->privates['sulu_website.reference_store_pool'] ?? $container->load('getSuluWebsite_ReferenceStorePoolService')), ($container->privates['sulu_admin.property_metadata_min_max_value_resolver'] ??= new \Sulu\Bundle\AdminBundle\Metadata\SchemaMetadata\PropertyMetadataMinMaxValueResolver()));
    }
}
