<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_ContentRepository_EventSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.content_repository.event_subscriber' shared service.
     *
     * @return \Sulu\Component\Content\Repository\Serializer\SerializerEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_security.access_control_manager'] ?? self::getSuluSecurity_AccessControlManagerService($container));

        if (isset($container->privates['sulu_page.content_repository.event_subscriber'])) {
            return $container->privates['sulu_page.content_repository.event_subscriber'];
        }

        return $container->privates['sulu_page.content_repository.event_subscriber'] = new \Sulu\Component\Content\Repository\Serializer\SerializerEventListener($a, ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
