<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluActivity_DispatchSpecificDomainEventSubscriberService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_activity.dispatch_specific_domain_event_subscriber' shared service.
     *
     * @return \Sulu\Bundle\ActivityBundle\Application\Subscriber\DispatchSpecificDomainEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['sulu_activity.dispatch_specific_domain_event_subscriber'])) {
            return $container->privates['sulu_activity.dispatch_specific_domain_event_subscriber'];
        }

        return $container->privates['sulu_activity.dispatch_specific_domain_event_subscriber'] = new \Sulu\Bundle\ActivityBundle\Application\Subscriber\DispatchSpecificDomainEventSubscriber($a);
    }
}
