<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_CollectionManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.collection_manager' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Collection\Manager\CollectionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.collection_manager'] = new \Sulu\Bundle\MediaBundle\Collection\Manager\CollectionManager(($container->services['sulu_media.collection_repository'] ?? self::getSuluMedia_CollectionRepositoryService($container)), ($container->services['sulu.repository.media'] ?? self::getSulu_Repository_MediaService($container)), ($container->services['sulu_media.format_manager'] ?? self::getSuluMedia_FormatManagerService($container)), ($container->services['sulu.repository.user'] ?? self::getSulu_Repository_UserService($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_activity.domain_event_collector'] ?? self::getSuluActivity_DomainEventCollectorService($container)), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['sulu_trash.trash_manager'] ?? self::getSuluTrash_TrashManagerService($container)), 'sulu-50x50', $container->parameters['sulu_security.permissions']);
    }
}
