<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_RepositoryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_custom_urls.repository' shared service.
     *
     * @return \Sulu\Component\CustomUrl\Repository\CustomUrlRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['sulu_custom_urls.repository'])) {
            return $container->privates['sulu_custom_urls.repository'];
        }
        $b = ($container->services['sulu_page.content_repository'] ?? self::getSuluPage_ContentRepositoryService($container));

        if (isset($container->privates['sulu_custom_urls.repository'])) {
            return $container->privates['sulu_custom_urls.repository'];
        }
        $c = ($container->services['sulu_security.user_manager'] ?? $container->load('getSuluSecurity_UserManagerService'));

        if (isset($container->privates['sulu_custom_urls.repository'])) {
            return $container->privates['sulu_custom_urls.repository'];
        }

        return $container->privates['sulu_custom_urls.repository'] = new \Sulu\Component\CustomUrl\Repository\CustomUrlRepository($a, $b, ($container->privates['sulu_custom_urls.domain_generator'] ?? $container->load('getSuluCustomUrls_DomainGeneratorService')), $c);
    }
}
