<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_SmartContent_DataProvider_QueryBuilderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_snippet.smart_content.data_provider.query_builder' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Content\SnippetQueryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_snippet.smart_content.data_provider.query_builder'] = new \Sulu\Bundle\SnippetBundle\Content\SnippetQueryBuilder(($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService')), ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container)), 'i18n');
    }
}
