<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Command_PhpcrCleanupService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.command.phpcr_cleanup' shared service.
     *
     * @return \Sulu\Bundle\DocumentManagerBundle\Command\PHPCRCleanupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_document_manager.command.phpcr_cleanup'] = $instance = new \Sulu\Bundle\DocumentManagerBundle\Command\PHPCRCleanupCommand(($container->services['doctrine_phpcr.session'] ?? self::getDoctrinePhpcr_SessionService($container)), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), ($container->services['services_resetter'] ?? $container->load('getServicesResetterService')), \dirname(__DIR__, 5));

        $instance->setName('sulu:document:phpcr-cleanup');
        $instance->setDescription('Cleanup the PHPCR repository and remove unused properties.');

        return $instance;
    }
}
