<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_Teaser_ManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.teaser.manager' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Teaser\TeaserManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_page.teaser.provider_pool'] ?? $container->load('getSuluPage_Teaser_ProviderPoolService'));

        if (isset($container->privates['sulu_page.teaser.manager'])) {
            return $container->privates['sulu_page.teaser.manager'];
        }

        return $container->privates['sulu_page.teaser.manager'] = new \Sulu\Bundle\PageBundle\Teaser\TeaserManager($a);
    }
}
