<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_PathBuilderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.path_builder' shared service.
     *
     * @return \Sulu\Component\DocumentManager\PathBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_document_manager.path_builder'] = new \Sulu\Component\DocumentManager\PathBuilder(($container->privates['sulu_document_manager.path_segment_registry'] ?? self::getSuluDocumentManager_PathSegmentRegistryService($container)));
    }
}
