<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSnippet_Content_SingleSnippetSelectionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_snippet.content.single_snippet_selection' shared service.
     *
     * @return \Sulu\Bundle\SnippetBundle\Content\SingleSnippetSelection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_snippet.content.single_snippet_selection'] = new \Sulu\Bundle\SnippetBundle\Content\SingleSnippetSelection(($container->services['sulu_snippet.resolver'] ?? $container->load('getSuluSnippet_ResolverService')), ($container->services['sulu_snippet.default_snippet.manager'] ?? $container->load('getSuluSnippet_DefaultSnippet_ManagerService')), ($container->services['sulu_snippet.reference_store.snippet'] ??= new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()), ($container->services['sulu_snippet.reference_store.snippet_area'] ??= new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore()));
    }
}
