<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_PagesSitemapProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.pages_sitemap_provider' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Sitemap\PagesSitemapProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_page.pages_sitemap_provider'] = new \Sulu\Bundle\PageBundle\Sitemap\PagesSitemapProvider(($container->services['sulu_page.content_repository'] ?? self::getSuluPage_ContentRepositoryService($container)), ($container->services['sulu_core.webspace.webspace_manager'] ?? self::getSuluCore_Webspace_WebspaceManagerService($container)), 'dev', ($container->privates['sulu_security.access_control_manager'] ?? self::getSuluSecurity_AccessControlManagerService($container)));
    }
}
