<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Suscriber_Behavior_AuthorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.suscriber.behavior.author' shared service.
     *
     * @return \Sulu\Component\Content\Document\Subscriber\AuthorSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.metadata_factory'] ?? self::getSuluDocumentManager_MetadataFactoryService($container));

        if (isset($container->privates['sulu_document_manager.suscriber.behavior.author'])) {
            return $container->privates['sulu_document_manager.suscriber.behavior.author'];
        }

        return $container->privates['sulu_document_manager.suscriber.behavior.author'] = new \Sulu\Component\Content\Document\Subscriber\AuthorSubscriber(($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)), ($container->services['sulu.repository.user'] ?? self::getSulu_Repository_UserService($container)), $a);
    }
}
