<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCustomUrls_CustomUrlControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_custom_urls.custom_url_controller' shared service.
     *
     * @return \Sulu\Bundle\CustomUrlBundle\Controller\CustomUrlController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_custom_urls.custom_url_controller'] = new \Sulu\Bundle\CustomUrlBundle\Controller\CustomUrlController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu_custom_urls.manager'] ?? $container->load('getSuluCustomUrls_ManagerService')), ($container->services['sulu_document_manager.document_manager'] ?? self::getSuluDocumentManager_DocumentManagerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
