<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluTag_TwigExtensionService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_tag.twig_extension' shared service.
     *
     * @return \Sulu\Bundle\TagBundle\Twig\TagTwigExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_tag.tag_manager'] ?? self::getSuluTag_TagManagerService($container));

        if (isset($container->privates['sulu_tag.twig_extension'])) {
            return $container->privates['sulu_tag.twig_extension'];
        }
        $b = ($container->services['sulu_core.array_serializer'] ?? $container->load('getSuluCore_ArraySerializerService'));

        if (isset($container->privates['sulu_tag.twig_extension'])) {
            return $container->privates['sulu_tag.twig_extension'];
        }

        return $container->privates['sulu_tag.twig_extension'] = new \Sulu\Bundle\TagBundle\Twig\TagTwigExtension($a, ($container->privates['sulu_tag.tag_request_handler'] ?? $container->load('getSuluTag_TagRequestHandlerService')), $b, ($container->privates['sulu_core.cache.memoize'] ?? $container->load('getSuluCore_Cache_MemoizeService')));
    }
}
