<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluHttpCache_CacheLifetime_EnhancerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_http_cache.cache_lifetime.enhancer' shared service.
     *
     * @return \Sulu\Bundle\HttpCacheBundle\CacheLifetime\CacheLifetimeEnhancer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_http_cache.cache_lifetime.enhancer'] = new \Sulu\Bundle\HttpCacheBundle\CacheLifetime\CacheLifetimeEnhancer(($container->privates['sulu_http_cache.cache_lifetime.resolver'] ??= new \Sulu\Bundle\HttpCacheBundle\CacheLifetime\CacheLifetimeResolver()), 240, 240, ($container->privates['sulu_http_cache.cache_lifetime.request_store'] ?? $container->load('getSuluHttpCache_CacheLifetime_RequestStoreService')));
    }
}
