<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_GroupRepositoryService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_security.group_repository' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Entity\GroupRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['sulu_security.group_repository'])) {
            return $container->privates['sulu_security.group_repository'];
        }

        return $container->privates['sulu_security.group_repository'] = $a->getRepository('Sulu\\Bundle\\SecurityBundle\\Entity\\Group');
    }
}
