<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluRoute_RouteControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_route.route_controller' shared service.
     *
     * @return \Sulu\Bundle\RouteBundle\Controller\RouteController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_route.route_controller'] = new \Sulu\Bundle\RouteBundle\Controller\RouteController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->services['sulu.repository.route'] ?? $container->load('getSulu_Repository_RouteService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['sulu_route.generator.route_generator'] ?? $container->load('getSuluRoute_Generator_RouteGeneratorService')), [], ($container->privates['sulu_route.manager.conflict_resolver.auto_increment'] ?? $container->load('getSuluRoute_Manager_ConflictResolver_AutoIncrementService')), ($container->privates['sulu_activity.domain_event_collector'] ?? self::getSuluActivity_DomainEventCollectorService($container)));
    }
}
