<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluLocation_Geolocator_Service_NominatimService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_location.geolocator.service.nominatim' shared service.
     *
     * @return \Sulu\Bundle\LocationBundle\Geolocator\Service\NominatimGeolocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_location.geolocator.service.nominatim'] = new \Sulu\Bundle\LocationBundle\Geolocator\Service\NominatimGeolocator(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), 'https://nominatim.openstreetmap.org/search', '');
    }
}
