<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_MediaControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_media.media_controller' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Controller\MediaController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_media.media_controller'] = new \Sulu\Bundle\MediaBundle\Controller\MediaController(($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['sulu_media.media_manager'] ?? self::getSuluMedia_MediaManagerService($container)), ($container->services['sulu_media.format_manager'] ?? self::getSuluMedia_FormatManagerService($container)), ($container->services['sulu_core.doctrine_rest_helper'] ?? $container->load('getSuluCore_DoctrineRestHelperService')), ($container->services['sulu_core.doctrine_list_builder_factory'] ?? $container->load('getSuluCore_DoctrineListBuilderFactoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['sulu_media.storage'] ?? self::getSuluMedia_StorageService($container)), ($container->services['sulu_media.collection_repository'] ?? self::getSuluMedia_CollectionRepositoryService($container)), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['sulu_core.list_builder.field_descriptor_factory'] ?? $container->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService')), 'Sulu\\Bundle\\MediaBundle\\Entity\\Media', 'Sulu\\Bundle\\MediaBundle\\Entity\\Collection', ($container->privates['sulu_media.media_list_builder_factory'] ?? $container->load('getSuluMedia_MediaListBuilderFactoryService')), ($container->privates['sulu_media.media_list_representation_factory'] ?? $container->load('getSuluMedia_MediaListRepresentationFactoryService')));
    }
}
