<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluSecurity_PermissionControllerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_security.permission_controller' shared service.
     *
     * @return \Sulu\Bundle\SecurityBundle\Controller\PermissionController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu_security.permission_controller'] = new \Sulu\Bundle\SecurityBundle\Controller\PermissionController(($container->privates['sulu_security.access_control_manager'] ?? self::getSuluSecurity_AccessControlManagerService($container)), ($container->services['sulu_security.security_checker'] ?? self::getSuluSecurity_SecurityCheckerService($container)), ($container->services['sulu.repository.role'] ?? self::getSulu_Repository_RoleService($container)), ($container->services['fos_rest.view_handler'] ?? $container->load('getFosRest_ViewHandlerService')), $container->parameters['sulu_admin.resources']);
    }
}
