<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAdmin_InfoCommandService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_admin.info_command' shared service.
     *
     * @return \Sulu\Bundle\AdminBundle\Command\InfoCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_admin.info_command'] = $instance = new \Sulu\Bundle\AdminBundle\Command\InfoCommand('_._._');

        $instance->setName('sulu:admin:info');

        return $instance;
    }
}
