<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Webspace_SettingsManagerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.webspace.settings_manager' shared service.
     *
     * @return \Sulu\Component\Webspace\Settings\SettingsManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_document_manager.session_manager'] ?? $container->load('getSuluDocumentManager_SessionManagerService'));

        if (isset($container->privates['sulu_core.webspace.settings_manager'])) {
            return $container->privates['sulu_core.webspace.settings_manager'];
        }
        $b = ($container->services['sulu.phpcr.session'] ?? self::getSulu_Phpcr_SessionService($container));

        if (isset($container->privates['sulu_core.webspace.settings_manager'])) {
            return $container->privates['sulu_core.webspace.settings_manager'];
        }

        return $container->privates['sulu_core.webspace.settings_manager'] = new \Sulu\Component\Webspace\Settings\SettingsManager($a, $b);
    }
}
