<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluCore_Webspace_UrlProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_core.webspace.url_provider' shared service.
     *
     * @return \Sulu\Component\Webspace\Url\WebspaceUrlChainProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['sulu_custom_urls.url_provider'] ?? $container->load('getSuluCustomUrls_UrlProviderService'));

        if (isset($container->privates['sulu_core.webspace.url_provider'])) {
            return $container->privates['sulu_core.webspace.url_provider'];
        }

        return $container->privates['sulu_core.webspace.url_provider'] = new \Sulu\Component\Webspace\Url\WebspaceUrlChainProvider([($container->privates['sulu_core.webspace.url_provider.default'] ??= new \Sulu\Component\Webspace\Url\WebspaceUrlProvider()), $a]);
    }
}
