<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluPage_ReferenceProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_page.reference_provider' shared service.
     *
     * @return \Sulu\Bundle\PageBundle\Reference\Provider\PageReferenceProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService'));

        if (isset($container->privates['sulu_page.reference_provider'])) {
            return $container->privates['sulu_page.reference_provider'];
        }
        $b = ($container->privates['sulu_reference.reference_repository'] ?? $container->load('getSuluReference_ReferenceRepositoryService'));

        if (isset($container->privates['sulu_page.reference_provider'])) {
            return $container->privates['sulu_page.reference_provider'];
        }

        return $container->privates['sulu_page.reference_provider'] = new \Sulu\Bundle\PageBundle\Reference\Provider\PageReferenceProvider(($container->services['sulu.content.type_manager'] ?? self::getSulu_Content_TypeManagerService($container)), ($container->services['sulu.content.structure_manager'] ?? self::getSulu_Content_StructureManagerService($container)), $a, $b);
    }
}
