<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluDocumentManager_Suscriber_Behavior_BlameService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_document_manager.suscriber.behavior.blame' shared service.
     *
     * @return \Sulu\Component\Content\Document\Subscriber\BlameSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_document_manager.suscriber.behavior.blame'] = new \Sulu\Component\Content\Document\Subscriber\BlameSubscriber(($container->services['sulu_document_manager.property_encoder'] ?? self::getSuluDocumentManager_PropertyEncoderService($container)));
    }
}
