<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluWebsite_Resolver_StructureService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu_website.resolver.structure' shared service.
     *
     * @return \Sulu\Bundle\WebsiteBundle\Resolver\StructureResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['sulu_page.extension.manager'] ?? $container->load('getSuluPage_Extension_ManagerService'));

        if (isset($container->services['sulu_website.resolver.structure'])) {
            return $container->services['sulu_website.resolver.structure'];
        }

        return $container->services['sulu_website.resolver.structure'] = new \Sulu\Bundle\WebsiteBundle\Resolver\StructureResolver(($container->services['sulu.content.type_manager'] ?? self::getSulu_Content_TypeManagerService($container)), $a, $container->parameters['sulu_website.enabled_twig_attributes']);
    }
}
