<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSulu_Content_PathCleaner_ReplacerLoader_FileLocatorService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'sulu.content.path_cleaner.replacer_loader.file_locator' shared service.
     *
     * @return \Symfony\Component\Config\FileLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['sulu.content.path_cleaner.replacer_loader.file_locator'] = new \Symfony\Component\Config\FileLocator();
    }
}
