<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluAudienceTargeting_Rules_ReferrerService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_audience_targeting.rules.referrer' shared service.
     *
     * @return \Sulu\Bundle\AudienceTargetingBundle\Rule\ReferrerRule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['sulu_audience_targeting.rules.referrer'] = new \Sulu\Bundle\AudienceTargetingBundle\Rule\ReferrerRule(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['translator'] ?? self::getTranslatorService($container)), 'X-Forwarded-Referrer');
    }
}
