<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuluMedia_Command_InitService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'sulu_media.command.init' shared service.
     *
     * @return \Sulu\Bundle\MediaBundle\Command\InitCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['sulu_media.command.init'] = $instance = new \Sulu\Bundle\MediaBundle\Command\InitCommand(($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), (\dirname(__DIR__, 5).'/public/uploads/media'));

        $instance->setName('sulu:media:init');
        $instance->setDescription('Init Sulu Media Bundle');

        return $instance;
    }
}
