<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestUserProviderService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'test_user_provider' shared service.
     *
     * @return \Sulu\Bundle\TestBundle\Testing\TestUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['test_user_provider'])) {
            return $container->services['test_user_provider'];
        }
        $b = ($container->services['sulu.repository.contact'] ?? $container->load('getSulu_Repository_ContactService'));

        if (isset($container->services['test_user_provider'])) {
            return $container->services['test_user_provider'];
        }
        $c = ($container->services['sulu.repository.user'] ?? self::getSulu_Repository_UserService($container));

        if (isset($container->services['test_user_provider'])) {
            return $container->services['test_user_provider'];
        }
        $d = ($container->privates['sulu_security.user_provider'] ?? $container->load('getSuluSecurity_UserProviderService'));

        if (isset($container->services['test_user_provider'])) {
            return $container->services['test_user_provider'];
        }

        return $container->services['test_user_provider'] = new \Sulu\Bundle\TestBundle\Testing\TestUserProvider($a, $b, $c, ($container->services['sulu_security.encoder_factory'] ?? $container->load('getSuluSecurity_EncoderFactoryService')), $d);
    }
}
