<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestVoterService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'test_voter' shared service.
     *
     * @return \Sulu\Bundle\TestBundle\Testing\TestVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['test_voter'] = new \Sulu\Bundle\TestBundle\Testing\TestVoter();
    }
}
