<?php

namespace ContainerQk9OUPX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Loader_NativeFilesystemService extends PERSPEQTIVE_SuluSnippetTabsBundle_Tests_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.loader.native_filesystem' shared service.
     *
     * @return \Twig\Loader\FilesystemLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['twig.loader.native_filesystem'] = $instance = new \Twig\Loader\FilesystemLoader([], \dirname(__DIR__, 5));

        $instance->addPath('/var/www/html/vendor/doctrine/doctrine-bundle/templates', 'Doctrine');
        $instance->addPath('/var/www/html/vendor/doctrine/doctrine-bundle/templates', '!Doctrine');
        $instance->addPath('/var/www/html/vendor/doctrine/phpcr-bundle/src/Resources/views', 'DoctrinePHPCR');
        $instance->addPath('/var/www/html/vendor/doctrine/phpcr-bundle/src/Resources/views', '!DoctrinePHPCR');
        $instance->addPath('/var/www/html/vendor/jms/serializer-bundle/Resources/views', 'JMSSerializer');
        $instance->addPath('/var/www/html/vendor/jms/serializer-bundle/Resources/views', '!JMSSerializer');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/views', 'SuluAdmin');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/views', '!SuluAdmin');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Resources/views', 'SuluPage');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Resources/views', '!SuluPage');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Resources/views', 'SuluSecurity');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/SecurityBundle/Resources/views', '!SuluSecurity');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Resources/views', 'SuluWebsite');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Resources/views', '!SuluWebsite');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/TestBundle/Resources/views', 'SuluTest');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/TestBundle/Resources/views', '!SuluTest');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Resources/views', 'SuluPreview');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/PreviewBundle/Resources/views', '!SuluPreview');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/AudienceTargetingBundle/Resources/views', 'SuluAudienceTargeting');
        $instance->addPath('/var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/AudienceTargetingBundle/Resources/views', '!SuluAudienceTargeting');
        $instance->addPath('/var/www/html/vendor/symfony/security-bundle/Resources/views', 'Security');
        $instance->addPath('/var/www/html/vendor/symfony/security-bundle/Resources/views', '!Security');
        $instance->addPath('/var/www/html/vendor/symfony/twig-bridge/Resources/views/Email', 'email');
        $instance->addPath('/var/www/html/vendor/symfony/twig-bridge/Resources/views/Email', '!email');
        $instance->addPath('/var/www/html/vendor/symfony/twig-bridge/Resources/views/Form');

        return $instance;
    }
}
