<?php
use Sulu\Component\Localization\Localization;
use Sulu\Component\Webspace\Manager\WebspaceCollection;
use Sulu\Component\Webspace\Portal;
use Sulu\Component\Webspace\PortalInformation;
use Sulu\Component\Webspace\Environment;
use Sulu\Component\Webspace\Security;
use Sulu\Component\Webspace\Segment;
use Sulu\Component\Webspace\Url;
use Sulu\Component\Webspace\CustomUrl;
use Sulu\Component\Webspace\Webspace;
use Sulu\Component\Webspace\Navigation;
use Sulu\Component\Webspace\NavigationContext;

/**
 * adminWebspaceCollectionCache
 *
 * DO NOT EDIT
 * This file is autogenerated by the Sulu Webspace component
 */
class adminWebspaceCollectionCache extends WebspaceCollection
{
    public function __construct()
    {
        $webspaceRefs = array();
        $portalRefs = array();
        $localizationRefs = array();
        $segmentRefs = array();
        $portalInformationRefs = array();

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('test');
        $webspace->setName("Test");
        // add localization to webspace
        $localization0 = new Localization('de', '');
        $localization0->setShadow('');
        $localization0->setDefault(true);
        $localization0->setXDefault('');
        $localizationRefs['test_de'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization('en', '');
        $localization0->setShadow('');
        $localization0->setDefault(false);
        $localization0->setXDefault('');
        $localizationRefs['test_en'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme


        $webspace->addTemplate('search', 'search/search');
        $webspace->addTemplate('error', 'error/error');
        $webspace->addDefaultTemplate('page', 'page');
        $webspace->addDefaultTemplate('home', 'home');

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main',     array(
                        'title' =>     array(
                        'en' => 'Main',
                                'de' => 'Main',
                )
,
                )
));
        $webspace->setNavigation($navigation);
        $webspace->setResourceLocatorStrategy('tree_full_edit');


        // new portal
        $portal = new Portal();
        $portal->setName('Test');
        $portal->setKey('test');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization('de', '');
        $localization->setDefault('1');
        $localization->setXDefault('');
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization('en', '');
        $localization->setDefault('');
        $localization->setXDefault('');
        $portal->addLocalization($localization);


        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('de');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(false);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('de');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(false);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('test');

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('de');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $environment->addUrl($url);

        // add environment url
        $url = new Url();
        $url->setUrl('{host}');
        $url->setLanguage('en');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(false);
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['test'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['test'] = $webspace;



        $portalInformationRefs['prod']['{host}'] = new PortalInformation(
            1,
            $webspaceRefs['test'],
            $portalRefs['test'],
            $localizationRefs['test_en'],
            '{host}',
            null,
            null,
            false,
            '{host}',
            5
        );

        $portalInformationRefs['dev']['{host}'] = new PortalInformation(
            1,
            $webspaceRefs['test'],
            $portalRefs['test'],
            $localizationRefs['test_en'],
            '{host}',
            null,
            null,
            false,
            '{host}',
            5
        );

        $portalInformationRefs['test']['{host}'] = new PortalInformation(
            1,
            $webspaceRefs['test'],
            $portalRefs['test'],
            $localizationRefs['test_en'],
            '{host}',
            null,
            null,
            false,
            '{host}',
            5
        );


        $this->setWebspaces($webspaceRefs);
        $this->setPortals($portalRefs);
        $this->setPortalInformations($portalInformationRefs);
    }
}


